// Code generated by ent, DO NOT EDIT.

package sourcemetric

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the sourcemetric type in the database.
	Label = "source_metric"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldSourceName holds the string denoting the source_name field in the database.
	FieldSourceName = "source_name"
	// FieldEwmaLatencyMs holds the string denoting the ewma_latency_ms field in the database.
	FieldEwmaLatencyMs = "ewma_latency_ms"
	// FieldLastLatencyMs holds the string denoting the last_latency_ms field in the database.
	FieldLastLatencyMs = "last_latency_ms"
	// FieldSearchCount holds the string denoting the search_count field in the database.
	FieldSearchCount = "search_count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldFailCount holds the string denoting the fail_count field in the database.
	FieldFailCount = "fail_count"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastErrorAt holds the string denoting the last_error_at field in the database.
	FieldLastErrorAt = "last_error_at"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldLastWarmedAt holds the string denoting the last_warmed_at field in the database.
	FieldLastWarmedAt = "last_warmed_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the sourcemetric in the database.
	Table = "source_metrics"
)

// Columns holds all SQL columns for sourcemetric fields.
var Columns = []string{
	FieldID,
	FieldSourceID,
	FieldSourceName,
	FieldEwmaLatencyMs,
	FieldLastLatencyMs,
	FieldSearchCount,
	FieldSuccessCount,
	FieldFailCount,
	FieldLastError,
	FieldLastErrorAt,
	FieldLastSuccessAt,
	FieldLastWarmedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSourceName holds the default value on creation for the "source_name" field.
	DefaultSourceName string
	// DefaultEwmaLatencyMs holds the default value on creation for the "ewma_latency_ms" field.
	DefaultEwmaLatencyMs int
	// DefaultLastLatencyMs holds the default value on creation for the "last_latency_ms" field.
	DefaultLastLatencyMs int
	// DefaultSearchCount holds the default value on creation for the "search_count" field.
	DefaultSearchCount int
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int
	// DefaultFailCount holds the default value on creation for the "fail_count" field.
	DefaultFailCount int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SourceMetric queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// BySourceName orders the results by the source_name field.
func BySourceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceName, opts...).ToFunc()
}

// ByEwmaLatencyMs orders the results by the ewma_latency_ms field.
func ByEwmaLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEwmaLatencyMs, opts...).ToFunc()
}

// ByLastLatencyMs orders the results by the last_latency_ms field.
func ByLastLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLatencyMs, opts...).ToFunc()
}

// BySearchCount orders the results by the search_count field.
func BySearchCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSearchCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByFailCount orders the results by the fail_count field.
func ByFailCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailCount, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastErrorAt orders the results by the last_error_at field.
func ByLastErrorAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorAt, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByLastWarmedAt orders the results by the last_warmed_at field.
func ByLastWarmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastWarmedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
