// Code generated by ent, DO NOT EDIT.

package sourcemetric

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSourceID, v))
}

// SourceName applies equality check predicate on the "source_name" field. It's identical to SourceNameEQ.
func SourceName(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSourceName, v))
}

// EwmaLatencyMs applies equality check predicate on the "ewma_latency_ms" field. It's identical to EwmaLatencyMsEQ.
func EwmaLatencyMs(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldEwmaLatencyMs, v))
}

// LastLatencyMs applies equality check predicate on the "last_latency_ms" field. It's identical to LastLatencyMsEQ.
func LastLatencyMs(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastLatencyMs, v))
}

// SearchCount applies equality check predicate on the "search_count" field. It's identical to SearchCountEQ.
func SearchCount(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSearchCount, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSuccessCount, v))
}

// FailCount applies equality check predicate on the "fail_count" field. It's identical to FailCountEQ.
func FailCount(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldFailCount, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastError, v))
}

// LastErrorAt applies equality check predicate on the "last_error_at" field. It's identical to LastErrorAtEQ.
func LastErrorAt(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastErrorAt, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastWarmedAt applies equality check predicate on the "last_warmed_at" field. It's identical to LastWarmedAtEQ.
func LastWarmedAt(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastWarmedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldContainsFold(FieldSourceID, v))
}

// SourceNameEQ applies the EQ predicate on the "source_name" field.
func SourceNameEQ(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSourceName, v))
}

// SourceNameNEQ applies the NEQ predicate on the "source_name" field.
func SourceNameNEQ(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldSourceName, v))
}

// SourceNameIn applies the In predicate on the "source_name" field.
func SourceNameIn(vs ...string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldSourceName, vs...))
}

// SourceNameNotIn applies the NotIn predicate on the "source_name" field.
func SourceNameNotIn(vs ...string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldSourceName, vs...))
}

// SourceNameGT applies the GT predicate on the "source_name" field.
func SourceNameGT(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldSourceName, v))
}

// SourceNameGTE applies the GTE predicate on the "source_name" field.
func SourceNameGTE(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldSourceName, v))
}

// SourceNameLT applies the LT predicate on the "source_name" field.
func SourceNameLT(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldSourceName, v))
}

// SourceNameLTE applies the LTE predicate on the "source_name" field.
func SourceNameLTE(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldSourceName, v))
}

// SourceNameContains applies the Contains predicate on the "source_name" field.
func SourceNameContains(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldContains(FieldSourceName, v))
}

// SourceNameHasPrefix applies the HasPrefix predicate on the "source_name" field.
func SourceNameHasPrefix(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldHasPrefix(FieldSourceName, v))
}

// SourceNameHasSuffix applies the HasSuffix predicate on the "source_name" field.
func SourceNameHasSuffix(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldHasSuffix(FieldSourceName, v))
}

// SourceNameEqualFold applies the EqualFold predicate on the "source_name" field.
func SourceNameEqualFold(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEqualFold(FieldSourceName, v))
}

// SourceNameContainsFold applies the ContainsFold predicate on the "source_name" field.
func SourceNameContainsFold(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldContainsFold(FieldSourceName, v))
}

// EwmaLatencyMsEQ applies the EQ predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldEwmaLatencyMs, v))
}

// EwmaLatencyMsNEQ applies the NEQ predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsNEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldEwmaLatencyMs, v))
}

// EwmaLatencyMsIn applies the In predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldEwmaLatencyMs, vs...))
}

// EwmaLatencyMsNotIn applies the NotIn predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsNotIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldEwmaLatencyMs, vs...))
}

// EwmaLatencyMsGT applies the GT predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsGT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldEwmaLatencyMs, v))
}

// EwmaLatencyMsGTE applies the GTE predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsGTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldEwmaLatencyMs, v))
}

// EwmaLatencyMsLT applies the LT predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsLT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldEwmaLatencyMs, v))
}

// EwmaLatencyMsLTE applies the LTE predicate on the "ewma_latency_ms" field.
func EwmaLatencyMsLTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldEwmaLatencyMs, v))
}

// LastLatencyMsEQ applies the EQ predicate on the "last_latency_ms" field.
func LastLatencyMsEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastLatencyMs, v))
}

// LastLatencyMsNEQ applies the NEQ predicate on the "last_latency_ms" field.
func LastLatencyMsNEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldLastLatencyMs, v))
}

// LastLatencyMsIn applies the In predicate on the "last_latency_ms" field.
func LastLatencyMsIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldLastLatencyMs, vs...))
}

// LastLatencyMsNotIn applies the NotIn predicate on the "last_latency_ms" field.
func LastLatencyMsNotIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldLastLatencyMs, vs...))
}

// LastLatencyMsGT applies the GT predicate on the "last_latency_ms" field.
func LastLatencyMsGT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldLastLatencyMs, v))
}

// LastLatencyMsGTE applies the GTE predicate on the "last_latency_ms" field.
func LastLatencyMsGTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldLastLatencyMs, v))
}

// LastLatencyMsLT applies the LT predicate on the "last_latency_ms" field.
func LastLatencyMsLT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldLastLatencyMs, v))
}

// LastLatencyMsLTE applies the LTE predicate on the "last_latency_ms" field.
func LastLatencyMsLTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldLastLatencyMs, v))
}

// SearchCountEQ applies the EQ predicate on the "search_count" field.
func SearchCountEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSearchCount, v))
}

// SearchCountNEQ applies the NEQ predicate on the "search_count" field.
func SearchCountNEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldSearchCount, v))
}

// SearchCountIn applies the In predicate on the "search_count" field.
func SearchCountIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldSearchCount, vs...))
}

// SearchCountNotIn applies the NotIn predicate on the "search_count" field.
func SearchCountNotIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldSearchCount, vs...))
}

// SearchCountGT applies the GT predicate on the "search_count" field.
func SearchCountGT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldSearchCount, v))
}

// SearchCountGTE applies the GTE predicate on the "search_count" field.
func SearchCountGTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldSearchCount, v))
}

// SearchCountLT applies the LT predicate on the "search_count" field.
func SearchCountLT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldSearchCount, v))
}

// SearchCountLTE applies the LTE predicate on the "search_count" field.
func SearchCountLTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldSearchCount, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldSuccessCount, v))
}

// FailCountEQ applies the EQ predicate on the "fail_count" field.
func FailCountEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldFailCount, v))
}

// FailCountNEQ applies the NEQ predicate on the "fail_count" field.
func FailCountNEQ(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldFailCount, v))
}

// FailCountIn applies the In predicate on the "fail_count" field.
func FailCountIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldFailCount, vs...))
}

// FailCountNotIn applies the NotIn predicate on the "fail_count" field.
func FailCountNotIn(vs ...int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldFailCount, vs...))
}

// FailCountGT applies the GT predicate on the "fail_count" field.
func FailCountGT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldFailCount, v))
}

// FailCountGTE applies the GTE predicate on the "fail_count" field.
func FailCountGTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldFailCount, v))
}

// FailCountLT applies the LT predicate on the "fail_count" field.
func FailCountLT(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldFailCount, v))
}

// FailCountLTE applies the LTE predicate on the "fail_count" field.
func FailCountLTE(v int) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldFailCount, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldContainsFold(FieldLastError, v))
}

// LastErrorAtEQ applies the EQ predicate on the "last_error_at" field.
func LastErrorAtEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastErrorAt, v))
}

// LastErrorAtNEQ applies the NEQ predicate on the "last_error_at" field.
func LastErrorAtNEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldLastErrorAt, v))
}

// LastErrorAtIn applies the In predicate on the "last_error_at" field.
func LastErrorAtIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldLastErrorAt, vs...))
}

// LastErrorAtNotIn applies the NotIn predicate on the "last_error_at" field.
func LastErrorAtNotIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldLastErrorAt, vs...))
}

// LastErrorAtGT applies the GT predicate on the "last_error_at" field.
func LastErrorAtGT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldLastErrorAt, v))
}

// LastErrorAtGTE applies the GTE predicate on the "last_error_at" field.
func LastErrorAtGTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldLastErrorAt, v))
}

// LastErrorAtLT applies the LT predicate on the "last_error_at" field.
func LastErrorAtLT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldLastErrorAt, v))
}

// LastErrorAtLTE applies the LTE predicate on the "last_error_at" field.
func LastErrorAtLTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldLastErrorAt, v))
}

// LastErrorAtIsNil applies the IsNil predicate on the "last_error_at" field.
func LastErrorAtIsNil() predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIsNull(FieldLastErrorAt))
}

// LastErrorAtNotNil applies the NotNil predicate on the "last_error_at" field.
func LastErrorAtNotNil() predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotNull(FieldLastErrorAt))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotNull(FieldLastSuccessAt))
}

// LastWarmedAtEQ applies the EQ predicate on the "last_warmed_at" field.
func LastWarmedAtEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldLastWarmedAt, v))
}

// LastWarmedAtNEQ applies the NEQ predicate on the "last_warmed_at" field.
func LastWarmedAtNEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldLastWarmedAt, v))
}

// LastWarmedAtIn applies the In predicate on the "last_warmed_at" field.
func LastWarmedAtIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldLastWarmedAt, vs...))
}

// LastWarmedAtNotIn applies the NotIn predicate on the "last_warmed_at" field.
func LastWarmedAtNotIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldLastWarmedAt, vs...))
}

// LastWarmedAtGT applies the GT predicate on the "last_warmed_at" field.
func LastWarmedAtGT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldLastWarmedAt, v))
}

// LastWarmedAtGTE applies the GTE predicate on the "last_warmed_at" field.
func LastWarmedAtGTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldLastWarmedAt, v))
}

// LastWarmedAtLT applies the LT predicate on the "last_warmed_at" field.
func LastWarmedAtLT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldLastWarmedAt, v))
}

// LastWarmedAtLTE applies the LTE predicate on the "last_warmed_at" field.
func LastWarmedAtLTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldLastWarmedAt, v))
}

// LastWarmedAtIsNil applies the IsNil predicate on the "last_warmed_at" field.
func LastWarmedAtIsNil() predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIsNull(FieldLastWarmedAt))
}

// LastWarmedAtNotNil applies the NotNil predicate on the "last_warmed_at" field.
func LastWarmedAtNotNil() predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotNull(FieldLastWarmedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SourceMetric {
	return predicate.SourceMetric(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SourceMetric) predicate.SourceMetric {
	return predicate.SourceMetric(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SourceMetric) predicate.SourceMetric {
	return predicate.SourceMetric(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SourceMetric) predicate.SourceMetric {
	return predicate.SourceMetric(sql.NotPredicates(p))
}
