// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "protected", Type: field.TypeBool, Default: false},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// ChaptersColumns holds the columns for the "chapters" table.
	ChaptersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "chapter_key", Type: field.TypeString},
		{Name: "number", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"wanted", "downloading", "downloaded", "upgrade_available", "upgrading", "failed", "permanently_failed", "superseded"}, Default: "wanted"},
		{Name: "satisfied_importance", Type: field.TypeInt, Nullable: true},
		{Name: "page_count", Type: field.TypeInt, Nullable: true},
		{Name: "filename", Type: field.TypeString, Default: ""},
		{Name: "download_date", Type: field.TypeTime, Nullable: true},
		{Name: "first_downloaded_at", Type: field.TypeTime, Nullable: true},
		{Name: "retries", Type: field.TypeInt, Default: 0},
		{Name: "next_attempt_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "error_category", Type: field.TypeString, Default: ""},
		{Name: "read", Type: field.TypeBool, Default: false},
		{Name: "last_read_page", Type: field.TypeInt, Default: 0},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "satisfied_by_provider_id", Type: field.TypeUUID, Nullable: true},
		{Name: "series_id", Type: field.TypeUUID},
	}
	// ChaptersTable holds the schema information for the "chapters" table.
	ChaptersTable = &schema.Table{
		Name:       "chapters",
		Columns:    ChaptersColumns,
		PrimaryKey: []*schema.Column{ChaptersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chapters_series_providers_satisfied_by",
				Columns:    []*schema.Column{ChaptersColumns[16]},
				RefColumns: []*schema.Column{SeriesProvidersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "chapters_series_chapters",
				Columns:    []*schema.Column{ChaptersColumns[17]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "chapter_series_id_chapter_key",
				Unique:  true,
				Columns: []*schema.Column{ChaptersColumns[17], ChaptersColumns[1]},
			},
		},
	}
	// EtagCachesColumns holds the columns for the "etag_caches" table.
	EtagCachesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "etag", Type: field.TypeString, Default: ""},
		{Name: "last_modified", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EtagCachesTable holds the schema information for the "etag_caches" table.
	EtagCachesTable = &schema.Table{
		Name:       "etag_caches",
		Columns:    EtagCachesColumns,
		PrimaryKey: []*schema.Column{EtagCachesColumns[0]},
	}
	// HarvestedExtensionsColumns holds the columns for the "harvested_extensions" table.
	HarvestedExtensionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "pkg_name", Type: field.TypeString, Unique: true},
		{Name: "repo_url", Type: field.TypeString, Default: ""},
		{Name: "version_code", Type: field.TypeInt, Default: 0},
		{Name: "installed_version_code", Type: field.TypeInt, Default: 0},
		{Name: "version_name", Type: field.TypeString, Default: ""},
		{Name: "source_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "apk_sha256", Type: field.TypeString, Default: ""},
		{Name: "apk_cached", Type: field.TypeBool, Default: false},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// HarvestedExtensionsTable holds the schema information for the "harvested_extensions" table.
	HarvestedExtensionsTable = &schema.Table{
		Name:       "harvested_extensions",
		Columns:    HarvestedExtensionsColumns,
		PrimaryKey: []*schema.Column{HarvestedExtensionsColumns[0]},
	}
	// HarvestedReposColumns holds the columns for the "harvested_repos" table.
	HarvestedReposColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// HarvestedReposTable holds the schema information for the "harvested_repos" table.
	HarvestedReposTable = &schema.Table{
		Name:       "harvested_repos",
		Columns:    HarvestedReposColumns,
		PrimaryKey: []*schema.Column{HarvestedReposColumns[0]},
	}
	// ImportEntriesColumns holds the columns for the "import_entries" table.
	ImportEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "category", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "chapter_count", Type: field.TypeInt, Default: 0},
		{Name: "found", Type: field.TypeJSON, Nullable: true},
		{Name: "matched_source", Type: field.TypeJSON, Nullable: true},
		{Name: "scanned_at", Type: field.TypeTime},
	}
	// ImportEntriesTable holds the schema information for the "import_entries" table.
	ImportEntriesTable = &schema.Table{
		Name:       "import_entries",
		Columns:    ImportEntriesColumns,
		PrimaryKey: []*schema.Column{ImportEntriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "importentry_status",
				Unique:  false,
				Columns: []*schema.Column{ImportEntriesColumns[4]},
			},
		},
	}
	// LatestSeriesColumns holds the columns for the "latest_series" table.
	LatestSeriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "series_id", Type: field.TypeUUID, Unique: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "rank", Type: field.TypeInt, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// LatestSeriesTable holds the schema information for the "latest_series" table.
	LatestSeriesTable = &schema.Table{
		Name:       "latest_series",
		Columns:    LatestSeriesColumns,
		PrimaryKey: []*schema.Column{LatestSeriesColumns[0]},
	}
	// OwnersColumns holds the columns for the "owners" table.
	OwnersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OwnersTable holds the schema information for the "owners" table.
	OwnersTable = &schema.Table{
		Name:       "owners",
		Columns:    OwnersColumns,
		PrimaryKey: []*schema.Column{OwnersColumns[0]},
	}
	// PendingTrackPushesColumns holds the columns for the "pending_track_pushes" table.
	PendingTrackPushesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "track_binding_id", Type: field.TypeUUID, Unique: true},
		{Name: "chapter", Type: field.TypeFloat64},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "next_attempt_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PendingTrackPushesTable holds the schema information for the "pending_track_pushes" table.
	PendingTrackPushesTable = &schema.Table{
		Name:       "pending_track_pushes",
		Columns:    PendingTrackPushesColumns,
		PrimaryKey: []*schema.Column{PendingTrackPushesColumns[0]},
	}
	// ProviderChaptersColumns holds the columns for the "provider_chapters" table.
	ProviderChaptersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "chapter_key", Type: field.TypeString},
		{Name: "number", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Default: ""},
		{Name: "web_url", Type: field.TypeString, Default: ""},
		{Name: "provider_upload_date", Type: field.TypeTime, Nullable: true},
		{Name: "provider_index", Type: field.TypeInt, Default: 0},
		{Name: "page_count", Type: field.TypeInt, Nullable: true},
		{Name: "suwayomi_chapter_id", Type: field.TypeInt, Nullable: true},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "next_attempt_at", Type: field.TypeTime, Nullable: true},
		{Name: "series_provider_id", Type: field.TypeUUID},
	}
	// ProviderChaptersTable holds the schema information for the "provider_chapters" table.
	ProviderChaptersTable = &schema.Table{
		Name:       "provider_chapters",
		Columns:    ProviderChaptersColumns,
		PrimaryKey: []*schema.Column{ProviderChaptersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "provider_chapters_series_providers_provider_chapters",
				Columns:    []*schema.Column{ProviderChaptersColumns[13]},
				RefColumns: []*schema.Column{SeriesProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "providerchapter_series_provider_id_chapter_key",
				Unique:  true,
				Columns: []*schema.Column{ProviderChaptersColumns[13], ProviderChaptersColumns[1]},
			},
		},
	}
	// PushSubscriptionsColumns holds the columns for the "push_subscriptions" table.
	PushSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "endpoint", Type: field.TypeString, Unique: true},
		{Name: "p256dh", Type: field.TypeString},
		{Name: "auth", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_success_at", Type: field.TypeTime, Nullable: true},
		{Name: "failure_count", Type: field.TypeInt, Default: 0},
	}
	// PushSubscriptionsTable holds the schema information for the "push_subscriptions" table.
	PushSubscriptionsTable = &schema.Table{
		Name:       "push_subscriptions",
		Columns:    PushSubscriptionsColumns,
		PrimaryKey: []*schema.Column{PushSubscriptionsColumns[0]},
	}
	// SeriesColumns holds the columns for the "series" table.
	SeriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "cover_url", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "genres", Type: field.TypeJSON, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "alt_titles", Type: field.TypeJSON, Nullable: true},
		{Name: "authors", Type: field.TypeJSON, Nullable: true},
		{Name: "links", Type: field.TypeJSON, Nullable: true},
		{Name: "year", Type: field.TypeInt, Default: 0},
		{Name: "monitored", Type: field.TypeBool, Default: true},
		{Name: "completed", Type: field.TypeBool, Default: false},
		{Name: "notify_armed", Type: field.TypeBool, Default: false},
		{Name: "metadata_provider_id", Type: field.TypeUUID, Nullable: true},
		{Name: "metadata_source", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata_locked", Type: field.TypeBool, Default: false},
		{Name: "cover_file", Type: field.TypeString, Default: ""},
		{Name: "cover_source_url", Type: field.TypeString, Default: ""},
		{Name: "cover_version", Type: field.TypeString, Default: ""},
		{Name: "cover_source", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "category_id", Type: field.TypeUUID, Nullable: true},
	}
	// SeriesTable holds the schema information for the "series" table.
	SeriesTable = &schema.Table{
		Name:       "series",
		Columns:    SeriesColumns,
		PrimaryKey: []*schema.Column{SeriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "series_categories_series",
				Columns:    []*schema.Column{SeriesColumns[24]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "series_genres",
				Unique:  false,
				Columns: []*schema.Column{SeriesColumns[6]},
				Annotation: &entsql.IndexAnnotation{
					Type: "GIN",
				},
			},
			{
				Name:    "series_tags",
				Unique:  false,
				Columns: []*schema.Column{SeriesColumns[7]},
				Annotation: &entsql.IndexAnnotation{
					Type: "GIN",
				},
			},
		},
	}
	// SeriesProvidersColumns holds the columns for the "series_providers" table.
	SeriesProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "suwayomi_id", Type: field.TypeInt, Nullable: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "scanlator", Type: field.TypeString, Default: ""},
		{Name: "language", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Default: ""},
		{Name: "web_url", Type: field.TypeString, Default: ""},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "metadata", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "flags", Type: field.TypeUint32, Default: 0},
		{Name: "importance", Type: field.TypeInt, Default: 0},
		{Name: "ignore_fractional", Type: field.TypeBool, Default: false},
		{Name: "cover_url", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "series_id", Type: field.TypeUUID},
	}
	// SeriesProvidersTable holds the schema information for the "series_providers" table.
	SeriesProvidersTable = &schema.Table{
		Name:       "series_providers",
		Columns:    SeriesProvidersColumns,
		PrimaryKey: []*schema.Column{SeriesProvidersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "series_providers_series_providers",
				Columns:    []*schema.Column{SeriesProvidersColumns[17]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// SourceCircuitStatesColumns holds the columns for the "source_circuit_states" table.
	SourceCircuitStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "source_key", Type: field.TypeString, Unique: true},
		{Name: "consecutive_failures", Type: field.TypeInt, Default: 0},
		{Name: "cooldown_until", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SourceCircuitStatesTable holds the schema information for the "source_circuit_states" table.
	SourceCircuitStatesTable = &schema.Table{
		Name:       "source_circuit_states",
		Columns:    SourceCircuitStatesColumns,
		PrimaryKey: []*schema.Column{SourceCircuitStatesColumns[0]},
	}
	// SourceEventsColumns holds the columns for the "source_events" table.
	SourceEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "source", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SourceEventsTable holds the schema information for the "source_events" table.
	SourceEventsTable = &schema.Table{
		Name:       "source_events",
		Columns:    SourceEventsColumns,
		PrimaryKey: []*schema.Column{SourceEventsColumns[0]},
	}
	// SourceMetricsColumns holds the columns for the "source_metrics" table.
	SourceMetricsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "source_id", Type: field.TypeString, Unique: true},
		{Name: "source_name", Type: field.TypeString, Default: ""},
		{Name: "ewma_latency_ms", Type: field.TypeInt, Default: 0},
		{Name: "last_latency_ms", Type: field.TypeInt, Default: 0},
		{Name: "search_count", Type: field.TypeInt, Default: 0},
		{Name: "success_count", Type: field.TypeInt, Default: 0},
		{Name: "fail_count", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "last_error_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_success_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_warmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SourceMetricsTable holds the schema information for the "source_metrics" table.
	SourceMetricsTable = &schema.Table{
		Name:       "source_metrics",
		Columns:    SourceMetricsColumns,
		PrimaryKey: []*schema.Column{SourceMetricsColumns[0]},
	}
	// SourcePreferencesColumns holds the columns for the "source_preferences" table.
	SourcePreferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "source_id", Type: field.TypeInt64},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "value_type", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SourcePreferencesTable holds the schema information for the "source_preferences" table.
	SourcePreferencesTable = &schema.Table{
		Name:       "source_preferences",
		Columns:    SourcePreferencesColumns,
		PrimaryKey: []*schema.Column{SourcePreferencesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sourcepreference_source_id_key",
				Unique:  true,
				Columns: []*schema.Column{SourcePreferencesColumns[1], SourcePreferencesColumns[2]},
			},
		},
	}
	// SuwayomiSyncStatesColumns holds the columns for the "suwayomi_sync_states" table.
	SuwayomiSyncStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "last_synced_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "state", Type: field.TypeString, Default: ""},
		{Name: "series_provider_id", Type: field.TypeUUID, Unique: true},
	}
	// SuwayomiSyncStatesTable holds the schema information for the "suwayomi_sync_states" table.
	SuwayomiSyncStatesTable = &schema.Table{
		Name:       "suwayomi_sync_states",
		Columns:    SuwayomiSyncStatesColumns,
		PrimaryKey: []*schema.Column{SuwayomiSyncStatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "suwayomi_sync_states_series_providers_sync_state",
				Columns:    []*schema.Column{SuwayomiSyncStatesColumns[4]},
				RefColumns: []*schema.Column{SeriesProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "suwayomisyncstate_series_provider_id",
				Unique:  false,
				Columns: []*schema.Column{SuwayomiSyncStatesColumns[4]},
			},
		},
	}
	// TrackBindingsColumns holds the columns for the "track_bindings" table.
	TrackBindingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tracker_id", Type: field.TypeInt},
		{Name: "remote_id", Type: field.TypeString},
		{Name: "remote_url", Type: field.TypeString, Default: ""},
		{Name: "library_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "last_chapter_read", Type: field.TypeFloat64, Default: 0},
		{Name: "total_chapters", Type: field.TypeInt, Default: 0},
		{Name: "score", Type: field.TypeFloat64, Default: 0},
		{Name: "start_date", Type: field.TypeTime, Nullable: true},
		{Name: "finish_date", Type: field.TypeTime, Nullable: true},
		{Name: "private", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "series_id", Type: field.TypeUUID},
	}
	// TrackBindingsTable holds the schema information for the "track_bindings" table.
	TrackBindingsTable = &schema.Table{
		Name:       "track_bindings",
		Columns:    TrackBindingsColumns,
		PrimaryKey: []*schema.Column{TrackBindingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "track_bindings_series_track_bindings",
				Columns:    []*schema.Column{TrackBindingsColumns[15]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "trackbinding_series_id_tracker_id",
				Unique:  true,
				Columns: []*schema.Column{TrackBindingsColumns[15], TrackBindingsColumns[1]},
			},
		},
	}
	// TrackerConnectionsColumns holds the columns for the "tracker_connections" table.
	TrackerConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "tracker_id", Type: field.TypeInt, Unique: true},
		{Name: "access_token", Type: field.TypeString, Default: ""},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "token_type", Type: field.TypeString, Default: "Bearer"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "score_format", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "token_expired", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TrackerConnectionsTable holds the schema information for the "tracker_connections" table.
	TrackerConnectionsTable = &schema.Table{
		Name:       "tracker_connections",
		Columns:    TrackerConnectionsColumns,
		PrimaryKey: []*schema.Column{TrackerConnectionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		ChaptersTable,
		EtagCachesTable,
		HarvestedExtensionsTable,
		HarvestedReposTable,
		ImportEntriesTable,
		LatestSeriesTable,
		OwnersTable,
		PendingTrackPushesTable,
		ProviderChaptersTable,
		PushSubscriptionsTable,
		SeriesTable,
		SeriesProvidersTable,
		SettingsTable,
		SourceCircuitStatesTable,
		SourceEventsTable,
		SourceMetricsTable,
		SourcePreferencesTable,
		SuwayomiSyncStatesTable,
		TrackBindingsTable,
		TrackerConnectionsTable,
	}
)

func init() {
	ChaptersTable.ForeignKeys[0].RefTable = SeriesProvidersTable
	ChaptersTable.ForeignKeys[1].RefTable = SeriesTable
	ProviderChaptersTable.ForeignKeys[0].RefTable = SeriesProvidersTable
	SeriesTable.ForeignKeys[0].RefTable = CategoriesTable
	SeriesProvidersTable.ForeignKeys[0].RefTable = SeriesTable
	SuwayomiSyncStatesTable.ForeignKeys[0].RefTable = SeriesProvidersTable
	TrackBindingsTable.ForeignKeys[0].RefTable = SeriesTable
}
