// Code generated by ent, DO NOT EDIT.

package providerchapter

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the providerchapter type in the database.
	Label = "provider_chapter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeriesProviderID holds the string denoting the series_provider_id field in the database.
	FieldSeriesProviderID = "series_provider_id"
	// FieldChapterKey holds the string denoting the chapter_key field in the database.
	FieldChapterKey = "chapter_key"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldWebURL holds the string denoting the web_url field in the database.
	FieldWebURL = "web_url"
	// FieldProviderUploadDate holds the string denoting the provider_upload_date field in the database.
	FieldProviderUploadDate = "provider_upload_date"
	// FieldProviderIndex holds the string denoting the provider_index field in the database.
	FieldProviderIndex = "provider_index"
	// FieldPageCount holds the string denoting the page_count field in the database.
	FieldPageCount = "page_count"
	// FieldSuwayomiChapterID holds the string denoting the suwayomi_chapter_id field in the database.
	FieldSuwayomiChapterID = "suwayomi_chapter_id"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// EdgeSeriesProvider holds the string denoting the series_provider edge name in mutations.
	EdgeSeriesProvider = "series_provider"
	// Table holds the table name of the providerchapter in the database.
	Table = "provider_chapters"
	// SeriesProviderTable is the table that holds the series_provider relation/edge.
	SeriesProviderTable = "provider_chapters"
	// SeriesProviderInverseTable is the table name for the SeriesProvider entity.
	// It exists in this package in order to avoid circular dependency with the "seriesprovider" package.
	SeriesProviderInverseTable = "series_providers"
	// SeriesProviderColumn is the table column denoting the series_provider relation/edge.
	SeriesProviderColumn = "series_provider_id"
)

// Columns holds all SQL columns for providerchapter fields.
var Columns = []string{
	FieldID,
	FieldSeriesProviderID,
	FieldChapterKey,
	FieldNumber,
	FieldName,
	FieldURL,
	FieldWebURL,
	FieldProviderUploadDate,
	FieldProviderIndex,
	FieldPageCount,
	FieldSuwayomiChapterID,
	FieldAttempts,
	FieldLastError,
	FieldNextAttemptAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// DefaultWebURL holds the default value on creation for the "web_url" field.
	DefaultWebURL string
	// DefaultProviderIndex holds the default value on creation for the "provider_index" field.
	DefaultProviderIndex int
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ProviderChapter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySeriesProviderID orders the results by the series_provider_id field.
func BySeriesProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeriesProviderID, opts...).ToFunc()
}

// ByChapterKey orders the results by the chapter_key field.
func ByChapterKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChapterKey, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByWebURL orders the results by the web_url field.
func ByWebURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebURL, opts...).ToFunc()
}

// ByProviderUploadDate orders the results by the provider_upload_date field.
func ByProviderUploadDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderUploadDate, opts...).ToFunc()
}

// ByProviderIndex orders the results by the provider_index field.
func ByProviderIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderIndex, opts...).ToFunc()
}

// ByPageCount orders the results by the page_count field.
func ByPageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageCount, opts...).ToFunc()
}

// BySuwayomiChapterID orders the results by the suwayomi_chapter_id field.
func BySuwayomiChapterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuwayomiChapterID, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// BySeriesProviderField orders the results by series_provider field.
func BySeriesProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeriesProviderStep(), sql.OrderByField(field, opts...))
	}
}
func newSeriesProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeriesProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SeriesProviderTable, SeriesProviderColumn),
	)
}
