// Code generated by ent, DO NOT EDIT.

package globalruntimeintent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldID, id))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldScope, v))
}

// DesiredRevision applies equality check predicate on the "desired_revision" field. It's identical to DesiredRevisionEQ.
func DesiredRevision(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldDesiredRevision, v))
}

// AppliedRevision applies equality check predicate on the "applied_revision" field. It's identical to AppliedRevisionEQ.
func AppliedRevision(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldAppliedRevision, v))
}

// LastApplyAttempt applies equality check predicate on the "last_apply_attempt" field. It's identical to LastApplyAttemptEQ.
func LastApplyAttempt(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldLastApplyAttempt, v))
}

// LastApplyError applies equality check predicate on the "last_apply_error" field. It's identical to LastApplyErrorEQ.
func LastApplyError(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldLastApplyError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldContainsFold(FieldScope, v))
}

// DesiredRevisionEQ applies the EQ predicate on the "desired_revision" field.
func DesiredRevisionEQ(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldDesiredRevision, v))
}

// DesiredRevisionNEQ applies the NEQ predicate on the "desired_revision" field.
func DesiredRevisionNEQ(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldDesiredRevision, v))
}

// DesiredRevisionIn applies the In predicate on the "desired_revision" field.
func DesiredRevisionIn(vs ...int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldDesiredRevision, vs...))
}

// DesiredRevisionNotIn applies the NotIn predicate on the "desired_revision" field.
func DesiredRevisionNotIn(vs ...int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldDesiredRevision, vs...))
}

// DesiredRevisionGT applies the GT predicate on the "desired_revision" field.
func DesiredRevisionGT(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldDesiredRevision, v))
}

// DesiredRevisionGTE applies the GTE predicate on the "desired_revision" field.
func DesiredRevisionGTE(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldDesiredRevision, v))
}

// DesiredRevisionLT applies the LT predicate on the "desired_revision" field.
func DesiredRevisionLT(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldDesiredRevision, v))
}

// DesiredRevisionLTE applies the LTE predicate on the "desired_revision" field.
func DesiredRevisionLTE(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldDesiredRevision, v))
}

// AppliedRevisionEQ applies the EQ predicate on the "applied_revision" field.
func AppliedRevisionEQ(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldAppliedRevision, v))
}

// AppliedRevisionNEQ applies the NEQ predicate on the "applied_revision" field.
func AppliedRevisionNEQ(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldAppliedRevision, v))
}

// AppliedRevisionIn applies the In predicate on the "applied_revision" field.
func AppliedRevisionIn(vs ...int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldAppliedRevision, vs...))
}

// AppliedRevisionNotIn applies the NotIn predicate on the "applied_revision" field.
func AppliedRevisionNotIn(vs ...int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldAppliedRevision, vs...))
}

// AppliedRevisionGT applies the GT predicate on the "applied_revision" field.
func AppliedRevisionGT(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldAppliedRevision, v))
}

// AppliedRevisionGTE applies the GTE predicate on the "applied_revision" field.
func AppliedRevisionGTE(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldAppliedRevision, v))
}

// AppliedRevisionLT applies the LT predicate on the "applied_revision" field.
func AppliedRevisionLT(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldAppliedRevision, v))
}

// AppliedRevisionLTE applies the LTE predicate on the "applied_revision" field.
func AppliedRevisionLTE(v int64) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldAppliedRevision, v))
}

// LastApplyAttemptEQ applies the EQ predicate on the "last_apply_attempt" field.
func LastApplyAttemptEQ(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldLastApplyAttempt, v))
}

// LastApplyAttemptNEQ applies the NEQ predicate on the "last_apply_attempt" field.
func LastApplyAttemptNEQ(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldLastApplyAttempt, v))
}

// LastApplyAttemptIn applies the In predicate on the "last_apply_attempt" field.
func LastApplyAttemptIn(vs ...time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldLastApplyAttempt, vs...))
}

// LastApplyAttemptNotIn applies the NotIn predicate on the "last_apply_attempt" field.
func LastApplyAttemptNotIn(vs ...time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldLastApplyAttempt, vs...))
}

// LastApplyAttemptGT applies the GT predicate on the "last_apply_attempt" field.
func LastApplyAttemptGT(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldLastApplyAttempt, v))
}

// LastApplyAttemptGTE applies the GTE predicate on the "last_apply_attempt" field.
func LastApplyAttemptGTE(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldLastApplyAttempt, v))
}

// LastApplyAttemptLT applies the LT predicate on the "last_apply_attempt" field.
func LastApplyAttemptLT(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldLastApplyAttempt, v))
}

// LastApplyAttemptLTE applies the LTE predicate on the "last_apply_attempt" field.
func LastApplyAttemptLTE(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldLastApplyAttempt, v))
}

// LastApplyAttemptIsNil applies the IsNil predicate on the "last_apply_attempt" field.
func LastApplyAttemptIsNil() predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIsNull(FieldLastApplyAttempt))
}

// LastApplyAttemptNotNil applies the NotNil predicate on the "last_apply_attempt" field.
func LastApplyAttemptNotNil() predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotNull(FieldLastApplyAttempt))
}

// LastApplyErrorEQ applies the EQ predicate on the "last_apply_error" field.
func LastApplyErrorEQ(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldLastApplyError, v))
}

// LastApplyErrorNEQ applies the NEQ predicate on the "last_apply_error" field.
func LastApplyErrorNEQ(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldLastApplyError, v))
}

// LastApplyErrorIn applies the In predicate on the "last_apply_error" field.
func LastApplyErrorIn(vs ...string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldLastApplyError, vs...))
}

// LastApplyErrorNotIn applies the NotIn predicate on the "last_apply_error" field.
func LastApplyErrorNotIn(vs ...string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldLastApplyError, vs...))
}

// LastApplyErrorGT applies the GT predicate on the "last_apply_error" field.
func LastApplyErrorGT(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldLastApplyError, v))
}

// LastApplyErrorGTE applies the GTE predicate on the "last_apply_error" field.
func LastApplyErrorGTE(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldLastApplyError, v))
}

// LastApplyErrorLT applies the LT predicate on the "last_apply_error" field.
func LastApplyErrorLT(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldLastApplyError, v))
}

// LastApplyErrorLTE applies the LTE predicate on the "last_apply_error" field.
func LastApplyErrorLTE(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldLastApplyError, v))
}

// LastApplyErrorContains applies the Contains predicate on the "last_apply_error" field.
func LastApplyErrorContains(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldContains(FieldLastApplyError, v))
}

// LastApplyErrorHasPrefix applies the HasPrefix predicate on the "last_apply_error" field.
func LastApplyErrorHasPrefix(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldHasPrefix(FieldLastApplyError, v))
}

// LastApplyErrorHasSuffix applies the HasSuffix predicate on the "last_apply_error" field.
func LastApplyErrorHasSuffix(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldHasSuffix(FieldLastApplyError, v))
}

// LastApplyErrorEqualFold applies the EqualFold predicate on the "last_apply_error" field.
func LastApplyErrorEqualFold(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEqualFold(FieldLastApplyError, v))
}

// LastApplyErrorContainsFold applies the ContainsFold predicate on the "last_apply_error" field.
func LastApplyErrorContainsFold(v string) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldContainsFold(FieldLastApplyError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GlobalRuntimeIntent) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GlobalRuntimeIntent) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GlobalRuntimeIntent) predicate.GlobalRuntimeIntent {
	return predicate.GlobalRuntimeIntent(sql.NotPredicates(p))
}
