// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/chapter"
	"github.com/technobecet/tsundoku/internal/ent/series"
	"github.com/technobecet/tsundoku/internal/ent/seriesprovider"
)

// ChapterCreate is the builder for creating a Chapter entity.
type ChapterCreate struct {
	config
	mutation *ChapterMutation
	hooks    []Hook
}

// SetSeriesID sets the "series_id" field.
func (_c *ChapterCreate) SetSeriesID(v uuid.UUID) *ChapterCreate {
	_c.mutation.SetSeriesID(v)
	return _c
}

// SetChapterKey sets the "chapter_key" field.
func (_c *ChapterCreate) SetChapterKey(v string) *ChapterCreate {
	_c.mutation.SetChapterKey(v)
	return _c
}

// SetNumber sets the "number" field.
func (_c *ChapterCreate) SetNumber(v float64) *ChapterCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableNumber(v *float64) *ChapterCreate {
	if v != nil {
		_c.SetNumber(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *ChapterCreate) SetState(v chapter.State) *ChapterCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableState(v *chapter.State) *ChapterCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetSatisfiedByProviderID sets the "satisfied_by_provider_id" field.
func (_c *ChapterCreate) SetSatisfiedByProviderID(v uuid.UUID) *ChapterCreate {
	_c.mutation.SetSatisfiedByProviderID(v)
	return _c
}

// SetNillableSatisfiedByProviderID sets the "satisfied_by_provider_id" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableSatisfiedByProviderID(v *uuid.UUID) *ChapterCreate {
	if v != nil {
		_c.SetSatisfiedByProviderID(*v)
	}
	return _c
}

// SetSatisfiedImportance sets the "satisfied_importance" field.
func (_c *ChapterCreate) SetSatisfiedImportance(v int) *ChapterCreate {
	_c.mutation.SetSatisfiedImportance(v)
	return _c
}

// SetNillableSatisfiedImportance sets the "satisfied_importance" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableSatisfiedImportance(v *int) *ChapterCreate {
	if v != nil {
		_c.SetSatisfiedImportance(*v)
	}
	return _c
}

// SetPageCount sets the "page_count" field.
func (_c *ChapterCreate) SetPageCount(v int) *ChapterCreate {
	_c.mutation.SetPageCount(v)
	return _c
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_c *ChapterCreate) SetNillablePageCount(v *int) *ChapterCreate {
	if v != nil {
		_c.SetPageCount(*v)
	}
	return _c
}

// SetFilename sets the "filename" field.
func (_c *ChapterCreate) SetFilename(v string) *ChapterCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableFilename(v *string) *ChapterCreate {
	if v != nil {
		_c.SetFilename(*v)
	}
	return _c
}

// SetDownloadDate sets the "download_date" field.
func (_c *ChapterCreate) SetDownloadDate(v time.Time) *ChapterCreate {
	_c.mutation.SetDownloadDate(v)
	return _c
}

// SetNillableDownloadDate sets the "download_date" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableDownloadDate(v *time.Time) *ChapterCreate {
	if v != nil {
		_c.SetDownloadDate(*v)
	}
	return _c
}

// SetRetries sets the "retries" field.
func (_c *ChapterCreate) SetRetries(v int) *ChapterCreate {
	_c.mutation.SetRetries(v)
	return _c
}

// SetNillableRetries sets the "retries" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableRetries(v *int) *ChapterCreate {
	if v != nil {
		_c.SetRetries(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *ChapterCreate) SetNextAttemptAt(v time.Time) *ChapterCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableNextAttemptAt(v *time.Time) *ChapterCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ChapterCreate) SetLastError(v string) *ChapterCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableLastError(v *string) *ChapterCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetErrorCategory sets the "error_category" field.
func (_c *ChapterCreate) SetErrorCategory(v string) *ChapterCreate {
	_c.mutation.SetErrorCategory(v)
	return _c
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableErrorCategory(v *string) *ChapterCreate {
	if v != nil {
		_c.SetErrorCategory(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChapterCreate) SetID(v uuid.UUID) *ChapterCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChapterCreate) SetNillableID(v *uuid.UUID) *ChapterCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSeries sets the "series" edge to the Series entity.
func (_c *ChapterCreate) SetSeries(v *Series) *ChapterCreate {
	return _c.SetSeriesID(v.ID)
}

// SetSatisfiedByID sets the "satisfied_by" edge to the SeriesProvider entity by ID.
func (_c *ChapterCreate) SetSatisfiedByID(id uuid.UUID) *ChapterCreate {
	_c.mutation.SetSatisfiedByID(id)
	return _c
}

// SetNillableSatisfiedByID sets the "satisfied_by" edge to the SeriesProvider entity by ID if the given value is not nil.
func (_c *ChapterCreate) SetNillableSatisfiedByID(id *uuid.UUID) *ChapterCreate {
	if id != nil {
		_c = _c.SetSatisfiedByID(*id)
	}
	return _c
}

// SetSatisfiedBy sets the "satisfied_by" edge to the SeriesProvider entity.
func (_c *ChapterCreate) SetSatisfiedBy(v *SeriesProvider) *ChapterCreate {
	return _c.SetSatisfiedByID(v.ID)
}

// Mutation returns the ChapterMutation object of the builder.
func (_c *ChapterCreate) Mutation() *ChapterMutation {
	return _c.mutation
}

// Save creates the Chapter in the database.
func (_c *ChapterCreate) Save(ctx context.Context) (*Chapter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChapterCreate) SaveX(ctx context.Context) *Chapter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChapterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChapterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChapterCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := chapter.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Filename(); !ok {
		v := chapter.DefaultFilename
		_c.mutation.SetFilename(v)
	}
	if _, ok := _c.mutation.Retries(); !ok {
		v := chapter.DefaultRetries
		_c.mutation.SetRetries(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := chapter.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.ErrorCategory(); !ok {
		v := chapter.DefaultErrorCategory
		_c.mutation.SetErrorCategory(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chapter.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChapterCreate) check() error {
	if _, ok := _c.mutation.SeriesID(); !ok {
		return &ValidationError{Name: "series_id", err: errors.New(`ent: missing required field "Chapter.series_id"`)}
	}
	if _, ok := _c.mutation.ChapterKey(); !ok {
		return &ValidationError{Name: "chapter_key", err: errors.New(`ent: missing required field "Chapter.chapter_key"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Chapter.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := chapter.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Chapter.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "Chapter.filename"`)}
	}
	if _, ok := _c.mutation.Retries(); !ok {
		return &ValidationError{Name: "retries", err: errors.New(`ent: missing required field "Chapter.retries"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "Chapter.last_error"`)}
	}
	if _, ok := _c.mutation.ErrorCategory(); !ok {
		return &ValidationError{Name: "error_category", err: errors.New(`ent: missing required field "Chapter.error_category"`)}
	}
	if len(_c.mutation.SeriesIDs()) == 0 {
		return &ValidationError{Name: "series", err: errors.New(`ent: missing required edge "Chapter.series"`)}
	}
	return nil
}

func (_c *ChapterCreate) sqlSave(ctx context.Context) (*Chapter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChapterCreate) createSpec() (*Chapter, *sqlgraph.CreateSpec) {
	var (
		_node = &Chapter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chapter.Table, sqlgraph.NewFieldSpec(chapter.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChapterKey(); ok {
		_spec.SetField(chapter.FieldChapterKey, field.TypeString, value)
		_node.ChapterKey = value
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(chapter.FieldNumber, field.TypeFloat64, value)
		_node.Number = &value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(chapter.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.SatisfiedImportance(); ok {
		_spec.SetField(chapter.FieldSatisfiedImportance, field.TypeInt, value)
		_node.SatisfiedImportance = &value
	}
	if value, ok := _c.mutation.PageCount(); ok {
		_spec.SetField(chapter.FieldPageCount, field.TypeInt, value)
		_node.PageCount = &value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(chapter.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.DownloadDate(); ok {
		_spec.SetField(chapter.FieldDownloadDate, field.TypeTime, value)
		_node.DownloadDate = &value
	}
	if value, ok := _c.mutation.Retries(); ok {
		_spec.SetField(chapter.FieldRetries, field.TypeInt, value)
		_node.Retries = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(chapter.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(chapter.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.ErrorCategory(); ok {
		_spec.SetField(chapter.FieldErrorCategory, field.TypeString, value)
		_node.ErrorCategory = value
	}
	if nodes := _c.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.SeriesTable,
			Columns: []string{chapter.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeriesID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SatisfiedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chapter.SatisfiedByTable,
			Columns: []string{chapter.SatisfiedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesprovider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SatisfiedByProviderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChapterCreateBulk is the builder for creating many Chapter entities in bulk.
type ChapterCreateBulk struct {
	config
	err      error
	builders []*ChapterCreate
}

// Save creates the Chapter entities in the database.
func (_c *ChapterCreateBulk) Save(ctx context.Context) ([]*Chapter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chapter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChapterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChapterCreateBulk) SaveX(ctx context.Context) []*Chapter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChapterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChapterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
