// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/etagcache"
)

// EtagCacheCreate is the builder for creating a EtagCache entity.
type EtagCacheCreate struct {
	config
	mutation *EtagCacheMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (_c *EtagCacheCreate) SetURL(v string) *EtagCacheCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetEtag sets the "etag" field.
func (_c *EtagCacheCreate) SetEtag(v string) *EtagCacheCreate {
	_c.mutation.SetEtag(v)
	return _c
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_c *EtagCacheCreate) SetNillableEtag(v *string) *EtagCacheCreate {
	if v != nil {
		_c.SetEtag(*v)
	}
	return _c
}

// SetLastModified sets the "last_modified" field.
func (_c *EtagCacheCreate) SetLastModified(v string) *EtagCacheCreate {
	_c.mutation.SetLastModified(v)
	return _c
}

// SetNillableLastModified sets the "last_modified" field if the given value is not nil.
func (_c *EtagCacheCreate) SetNillableLastModified(v *string) *EtagCacheCreate {
	if v != nil {
		_c.SetLastModified(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EtagCacheCreate) SetUpdatedAt(v time.Time) *EtagCacheCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EtagCacheCreate) SetNillableUpdatedAt(v *time.Time) *EtagCacheCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EtagCacheCreate) SetID(v uuid.UUID) *EtagCacheCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EtagCacheCreate) SetNillableID(v *uuid.UUID) *EtagCacheCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the EtagCacheMutation object of the builder.
func (_c *EtagCacheCreate) Mutation() *EtagCacheMutation {
	return _c.mutation
}

// Save creates the EtagCache in the database.
func (_c *EtagCacheCreate) Save(ctx context.Context) (*EtagCache, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EtagCacheCreate) SaveX(ctx context.Context) *EtagCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EtagCacheCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EtagCacheCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EtagCacheCreate) defaults() {
	if _, ok := _c.mutation.Etag(); !ok {
		v := etagcache.DefaultEtag
		_c.mutation.SetEtag(v)
	}
	if _, ok := _c.mutation.LastModified(); !ok {
		v := etagcache.DefaultLastModified
		_c.mutation.SetLastModified(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := etagcache.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := etagcache.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EtagCacheCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "EtagCache.url"`)}
	}
	if _, ok := _c.mutation.Etag(); !ok {
		return &ValidationError{Name: "etag", err: errors.New(`ent: missing required field "EtagCache.etag"`)}
	}
	if _, ok := _c.mutation.LastModified(); !ok {
		return &ValidationError{Name: "last_modified", err: errors.New(`ent: missing required field "EtagCache.last_modified"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EtagCache.updated_at"`)}
	}
	return nil
}

func (_c *EtagCacheCreate) sqlSave(ctx context.Context) (*EtagCache, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EtagCacheCreate) createSpec() (*EtagCache, *sqlgraph.CreateSpec) {
	var (
		_node = &EtagCache{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(etagcache.Table, sqlgraph.NewFieldSpec(etagcache.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(etagcache.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Etag(); ok {
		_spec.SetField(etagcache.FieldEtag, field.TypeString, value)
		_node.Etag = value
	}
	if value, ok := _c.mutation.LastModified(); ok {
		_spec.SetField(etagcache.FieldLastModified, field.TypeString, value)
		_node.LastModified = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(etagcache.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EtagCacheCreateBulk is the builder for creating many EtagCache entities in bulk.
type EtagCacheCreateBulk struct {
	config
	err      error
	builders []*EtagCacheCreate
}

// Save creates the EtagCache entities in the database.
func (_c *EtagCacheCreateBulk) Save(ctx context.Context) ([]*EtagCache, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EtagCache, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EtagCacheMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EtagCacheCreateBulk) SaveX(ctx context.Context) []*EtagCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EtagCacheCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EtagCacheCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
