// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/technobecet/tsundoku/internal/ent/etagcache"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
)

// EtagCacheDelete is the builder for deleting a EtagCache entity.
type EtagCacheDelete struct {
	config
	hooks    []Hook
	mutation *EtagCacheMutation
}

// Where appends a list predicates to the EtagCacheDelete builder.
func (_d *EtagCacheDelete) Where(ps ...predicate.EtagCache) *EtagCacheDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EtagCacheDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EtagCacheDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EtagCacheDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(etagcache.Table, sqlgraph.NewFieldSpec(etagcache.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EtagCacheDeleteOne is the builder for deleting a single EtagCache entity.
type EtagCacheDeleteOne struct {
	_d *EtagCacheDelete
}

// Where appends a list predicates to the EtagCacheDelete builder.
func (_d *EtagCacheDeleteOne) Where(ps ...predicate.EtagCache) *EtagCacheDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EtagCacheDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{etagcache.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EtagCacheDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
