// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/category"
	"github.com/technobecet/tsundoku/internal/ent/chapter"
	"github.com/technobecet/tsundoku/internal/ent/series"
	"github.com/technobecet/tsundoku/internal/ent/seriesprovider"
	"github.com/technobecet/tsundoku/internal/ent/trackbinding"
	"github.com/technobecet/tsundoku/internal/metadata"
)

// SeriesCreate is the builder for creating a Series entity.
type SeriesCreate struct {
	config
	mutation *SeriesMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *SeriesCreate) SetTitle(v string) *SeriesCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *SeriesCreate) SetSlug(v string) *SeriesCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetCoverURL sets the "cover_url" field.
func (_c *SeriesCreate) SetCoverURL(v string) *SeriesCreate {
	_c.mutation.SetCoverURL(v)
	return _c
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCoverURL(v *string) *SeriesCreate {
	if v != nil {
		_c.SetCoverURL(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SeriesCreate) SetDescription(v string) *SeriesCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableDescription(v *string) *SeriesCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SeriesCreate) SetStatus(v string) *SeriesCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableStatus(v *string) *SeriesCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGenres sets the "genres" field.
func (_c *SeriesCreate) SetGenres(v []string) *SeriesCreate {
	_c.mutation.SetGenres(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *SeriesCreate) SetTags(v []string) *SeriesCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetAltTitles sets the "alt_titles" field.
func (_c *SeriesCreate) SetAltTitles(v []metadata.AltTitle) *SeriesCreate {
	_c.mutation.SetAltTitles(v)
	return _c
}

// SetAuthors sets the "authors" field.
func (_c *SeriesCreate) SetAuthors(v []metadata.Author) *SeriesCreate {
	_c.mutation.SetAuthors(v)
	return _c
}

// SetLinks sets the "links" field.
func (_c *SeriesCreate) SetLinks(v []metadata.Link) *SeriesCreate {
	_c.mutation.SetLinks(v)
	return _c
}

// SetYear sets the "year" field.
func (_c *SeriesCreate) SetYear(v int) *SeriesCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableYear(v *int) *SeriesCreate {
	if v != nil {
		_c.SetYear(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *SeriesCreate) SetCategoryID(v uuid.UUID) *SeriesCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCategoryID(v *uuid.UUID) *SeriesCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetMonitored sets the "monitored" field.
func (_c *SeriesCreate) SetMonitored(v bool) *SeriesCreate {
	_c.mutation.SetMonitored(v)
	return _c
}

// SetNillableMonitored sets the "monitored" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableMonitored(v *bool) *SeriesCreate {
	if v != nil {
		_c.SetMonitored(*v)
	}
	return _c
}

// SetCompleted sets the "completed" field.
func (_c *SeriesCreate) SetCompleted(v bool) *SeriesCreate {
	_c.mutation.SetCompleted(v)
	return _c
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCompleted(v *bool) *SeriesCreate {
	if v != nil {
		_c.SetCompleted(*v)
	}
	return _c
}

// SetNotifyArmed sets the "notify_armed" field.
func (_c *SeriesCreate) SetNotifyArmed(v bool) *SeriesCreate {
	_c.mutation.SetNotifyArmed(v)
	return _c
}

// SetNillableNotifyArmed sets the "notify_armed" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableNotifyArmed(v *bool) *SeriesCreate {
	if v != nil {
		_c.SetNotifyArmed(*v)
	}
	return _c
}

// SetMetadataProviderID sets the "metadata_provider_id" field.
func (_c *SeriesCreate) SetMetadataProviderID(v uuid.UUID) *SeriesCreate {
	_c.mutation.SetMetadataProviderID(v)
	return _c
}

// SetNillableMetadataProviderID sets the "metadata_provider_id" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableMetadataProviderID(v *uuid.UUID) *SeriesCreate {
	if v != nil {
		_c.SetMetadataProviderID(*v)
	}
	return _c
}

// SetMetadataSource sets the "metadata_source" field.
func (_c *SeriesCreate) SetMetadataSource(v *metadata.SourceRef) *SeriesCreate {
	_c.mutation.SetMetadataSource(v)
	return _c
}

// SetMetadataLocked sets the "metadata_locked" field.
func (_c *SeriesCreate) SetMetadataLocked(v bool) *SeriesCreate {
	_c.mutation.SetMetadataLocked(v)
	return _c
}

// SetNillableMetadataLocked sets the "metadata_locked" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableMetadataLocked(v *bool) *SeriesCreate {
	if v != nil {
		_c.SetMetadataLocked(*v)
	}
	return _c
}

// SetCoverFile sets the "cover_file" field.
func (_c *SeriesCreate) SetCoverFile(v string) *SeriesCreate {
	_c.mutation.SetCoverFile(v)
	return _c
}

// SetNillableCoverFile sets the "cover_file" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCoverFile(v *string) *SeriesCreate {
	if v != nil {
		_c.SetCoverFile(*v)
	}
	return _c
}

// SetCoverSourceURL sets the "cover_source_url" field.
func (_c *SeriesCreate) SetCoverSourceURL(v string) *SeriesCreate {
	_c.mutation.SetCoverSourceURL(v)
	return _c
}

// SetNillableCoverSourceURL sets the "cover_source_url" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCoverSourceURL(v *string) *SeriesCreate {
	if v != nil {
		_c.SetCoverSourceURL(*v)
	}
	return _c
}

// SetCoverVersion sets the "cover_version" field.
func (_c *SeriesCreate) SetCoverVersion(v string) *SeriesCreate {
	_c.mutation.SetCoverVersion(v)
	return _c
}

// SetNillableCoverVersion sets the "cover_version" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCoverVersion(v *string) *SeriesCreate {
	if v != nil {
		_c.SetCoverVersion(*v)
	}
	return _c
}

// SetCoverSource sets the "cover_source" field.
func (_c *SeriesCreate) SetCoverSource(v *metadata.SourceRef) *SeriesCreate {
	_c.mutation.SetCoverSource(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SeriesCreate) SetCreatedAt(v time.Time) *SeriesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableCreatedAt(v *time.Time) *SeriesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SeriesCreate) SetUpdatedAt(v time.Time) *SeriesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableUpdatedAt(v *time.Time) *SeriesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SeriesCreate) SetID(v uuid.UUID) *SeriesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableID(v *uuid.UUID) *SeriesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddProviderIDs adds the "providers" edge to the SeriesProvider entity by IDs.
func (_c *SeriesCreate) AddProviderIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddProviderIDs(ids...)
	return _c
}

// AddProviders adds the "providers" edges to the SeriesProvider entity.
func (_c *SeriesCreate) AddProviders(v ...*SeriesProvider) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProviderIDs(ids...)
}

// AddChapterIDs adds the "chapters" edge to the Chapter entity by IDs.
func (_c *SeriesCreate) AddChapterIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddChapterIDs(ids...)
	return _c
}

// AddChapters adds the "chapters" edges to the Chapter entity.
func (_c *SeriesCreate) AddChapters(v ...*Chapter) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChapterIDs(ids...)
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *SeriesCreate) SetCategory(v *Category) *SeriesCreate {
	return _c.SetCategoryID(v.ID)
}

// AddTrackBindingIDs adds the "track_bindings" edge to the TrackBinding entity by IDs.
func (_c *SeriesCreate) AddTrackBindingIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddTrackBindingIDs(ids...)
	return _c
}

// AddTrackBindings adds the "track_bindings" edges to the TrackBinding entity.
func (_c *SeriesCreate) AddTrackBindings(v ...*TrackBinding) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTrackBindingIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_c *SeriesCreate) Mutation() *SeriesMutation {
	return _c.mutation
}

// Save creates the Series in the database.
func (_c *SeriesCreate) Save(ctx context.Context) (*Series, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeriesCreate) SaveX(ctx context.Context) *Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SeriesCreate) defaults() {
	if _, ok := _c.mutation.CoverURL(); !ok {
		v := series.DefaultCoverURL
		_c.mutation.SetCoverURL(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := series.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := series.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Year(); !ok {
		v := series.DefaultYear
		_c.mutation.SetYear(v)
	}
	if _, ok := _c.mutation.Monitored(); !ok {
		v := series.DefaultMonitored
		_c.mutation.SetMonitored(v)
	}
	if _, ok := _c.mutation.Completed(); !ok {
		v := series.DefaultCompleted
		_c.mutation.SetCompleted(v)
	}
	if _, ok := _c.mutation.NotifyArmed(); !ok {
		v := series.DefaultNotifyArmed
		_c.mutation.SetNotifyArmed(v)
	}
	if _, ok := _c.mutation.MetadataLocked(); !ok {
		v := series.DefaultMetadataLocked
		_c.mutation.SetMetadataLocked(v)
	}
	if _, ok := _c.mutation.CoverFile(); !ok {
		v := series.DefaultCoverFile
		_c.mutation.SetCoverFile(v)
	}
	if _, ok := _c.mutation.CoverSourceURL(); !ok {
		v := series.DefaultCoverSourceURL
		_c.mutation.SetCoverSourceURL(v)
	}
	if _, ok := _c.mutation.CoverVersion(); !ok {
		v := series.DefaultCoverVersion
		_c.mutation.SetCoverVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := series.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := series.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := series.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeriesCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Series.title"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Series.slug"`)}
	}
	if _, ok := _c.mutation.CoverURL(); !ok {
		return &ValidationError{Name: "cover_url", err: errors.New(`ent: missing required field "Series.cover_url"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Series.description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Series.status"`)}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "Series.year"`)}
	}
	if _, ok := _c.mutation.Monitored(); !ok {
		return &ValidationError{Name: "monitored", err: errors.New(`ent: missing required field "Series.monitored"`)}
	}
	if _, ok := _c.mutation.Completed(); !ok {
		return &ValidationError{Name: "completed", err: errors.New(`ent: missing required field "Series.completed"`)}
	}
	if _, ok := _c.mutation.NotifyArmed(); !ok {
		return &ValidationError{Name: "notify_armed", err: errors.New(`ent: missing required field "Series.notify_armed"`)}
	}
	if _, ok := _c.mutation.MetadataLocked(); !ok {
		return &ValidationError{Name: "metadata_locked", err: errors.New(`ent: missing required field "Series.metadata_locked"`)}
	}
	if _, ok := _c.mutation.CoverFile(); !ok {
		return &ValidationError{Name: "cover_file", err: errors.New(`ent: missing required field "Series.cover_file"`)}
	}
	if _, ok := _c.mutation.CoverSourceURL(); !ok {
		return &ValidationError{Name: "cover_source_url", err: errors.New(`ent: missing required field "Series.cover_source_url"`)}
	}
	if _, ok := _c.mutation.CoverVersion(); !ok {
		return &ValidationError{Name: "cover_version", err: errors.New(`ent: missing required field "Series.cover_version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Series.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Series.updated_at"`)}
	}
	return nil
}

func (_c *SeriesCreate) sqlSave(ctx context.Context) (*Series, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeriesCreate) createSpec() (*Series, *sqlgraph.CreateSpec) {
	var (
		_node = &Series{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(series.Table, sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(series.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(series.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.CoverURL(); ok {
		_spec.SetField(series.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(series.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Genres(); ok {
		_spec.SetField(series.FieldGenres, field.TypeJSON, value)
		_node.Genres = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(series.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.AltTitles(); ok {
		_spec.SetField(series.FieldAltTitles, field.TypeJSON, value)
		_node.AltTitles = value
	}
	if value, ok := _c.mutation.Authors(); ok {
		_spec.SetField(series.FieldAuthors, field.TypeJSON, value)
		_node.Authors = value
	}
	if value, ok := _c.mutation.Links(); ok {
		_spec.SetField(series.FieldLinks, field.TypeJSON, value)
		_node.Links = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(series.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.Monitored(); ok {
		_spec.SetField(series.FieldMonitored, field.TypeBool, value)
		_node.Monitored = value
	}
	if value, ok := _c.mutation.Completed(); ok {
		_spec.SetField(series.FieldCompleted, field.TypeBool, value)
		_node.Completed = value
	}
	if value, ok := _c.mutation.NotifyArmed(); ok {
		_spec.SetField(series.FieldNotifyArmed, field.TypeBool, value)
		_node.NotifyArmed = value
	}
	if value, ok := _c.mutation.MetadataProviderID(); ok {
		_spec.SetField(series.FieldMetadataProviderID, field.TypeUUID, value)
		_node.MetadataProviderID = &value
	}
	if value, ok := _c.mutation.MetadataSource(); ok {
		_spec.SetField(series.FieldMetadataSource, field.TypeJSON, value)
		_node.MetadataSource = value
	}
	if value, ok := _c.mutation.MetadataLocked(); ok {
		_spec.SetField(series.FieldMetadataLocked, field.TypeBool, value)
		_node.MetadataLocked = value
	}
	if value, ok := _c.mutation.CoverFile(); ok {
		_spec.SetField(series.FieldCoverFile, field.TypeString, value)
		_node.CoverFile = value
	}
	if value, ok := _c.mutation.CoverSourceURL(); ok {
		_spec.SetField(series.FieldCoverSourceURL, field.TypeString, value)
		_node.CoverSourceURL = value
	}
	if value, ok := _c.mutation.CoverVersion(); ok {
		_spec.SetField(series.FieldCoverVersion, field.TypeString, value)
		_node.CoverVersion = value
	}
	if value, ok := _c.mutation.CoverSource(); ok {
		_spec.SetField(series.FieldCoverSource, field.TypeJSON, value)
		_node.CoverSource = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(series.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(series.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.ProvidersTable,
			Columns: []string{series.ProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesprovider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.ChaptersTable,
			Columns: []string{series.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   series.CategoryTable,
			Columns: []string{series.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TrackBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.TrackBindingsTable,
			Columns: []string{series.TrackBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackbinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SeriesCreateBulk is the builder for creating many Series entities in bulk.
type SeriesCreateBulk struct {
	config
	err      error
	builders []*SeriesCreate
}

// Save creates the Series entities in the database.
func (_c *SeriesCreateBulk) Save(ctx context.Context) ([]*Series, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Series, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeriesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeriesCreateBulk) SaveX(ctx context.Context) []*Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
