// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
	"github.com/technobecet/tsundoku/internal/ent/sourcebreakernotification"
)

// SourceBreakerNotificationUpdate is the builder for updating SourceBreakerNotification entities.
type SourceBreakerNotificationUpdate struct {
	config
	hooks    []Hook
	mutation *SourceBreakerNotificationMutation
}

// Where appends a list predicates to the SourceBreakerNotificationUpdate builder.
func (_u *SourceBreakerNotificationUpdate) Where(ps ...predicate.SourceBreakerNotification) *SourceBreakerNotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *SourceBreakerNotificationUpdate) SetSourceKey(v string) *SourceBreakerNotificationUpdate {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableSourceKey(v *string) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *SourceBreakerNotificationUpdate) SetEventType(v string) *SourceBreakerNotificationUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableEventType(v *string) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SourceBreakerNotificationUpdate) SetStatus(v string) *SourceBreakerNotificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableStatus(v *string) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SourceBreakerNotificationUpdate) SetErrorMessage(v string) *SourceBreakerNotificationUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableErrorMessage(v *string) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SourceBreakerNotificationUpdate) ClearErrorMessage() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorCategory sets the "error_category" field.
func (_u *SourceBreakerNotificationUpdate) SetErrorCategory(v string) *SourceBreakerNotificationUpdate {
	_u.mutation.SetErrorCategory(v)
	return _u
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableErrorCategory(v *string) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetErrorCategory(*v)
	}
	return _u
}

// SetEventRequested sets the "event_requested" field.
func (_u *SourceBreakerNotificationUpdate) SetEventRequested(v bool) *SourceBreakerNotificationUpdate {
	_u.mutation.SetEventRequested(v)
	return _u
}

// SetNillableEventRequested sets the "event_requested" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableEventRequested(v *bool) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetEventRequested(*v)
	}
	return _u
}

// SetHookRequested sets the "hook_requested" field.
func (_u *SourceBreakerNotificationUpdate) SetHookRequested(v bool) *SourceBreakerNotificationUpdate {
	_u.mutation.SetHookRequested(v)
	return _u
}

// SetNillableHookRequested sets the "hook_requested" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableHookRequested(v *bool) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetHookRequested(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *SourceBreakerNotificationUpdate) SetConsecutiveFailures(v int) *SourceBreakerNotificationUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableConsecutiveFailures(v *int) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *SourceBreakerNotificationUpdate) AddConsecutiveFailures(v int) *SourceBreakerNotificationUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *SourceBreakerNotificationUpdate) SetCooldownUntil(v time.Time) *SourceBreakerNotificationUpdate {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableCooldownUntil(v *time.Time) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *SourceBreakerNotificationUpdate) ClearCooldownUntil() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetFailingSince sets the "failing_since" field.
func (_u *SourceBreakerNotificationUpdate) SetFailingSince(v time.Time) *SourceBreakerNotificationUpdate {
	_u.mutation.SetFailingSince(v)
	return _u
}

// SetNillableFailingSince sets the "failing_since" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableFailingSince(v *time.Time) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetFailingSince(*v)
	}
	return _u
}

// ClearFailingSince clears the value of the "failing_since" field.
func (_u *SourceBreakerNotificationUpdate) ClearFailingSince() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearFailingSince()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SourceBreakerNotificationUpdate) SetLastError(v string) *SourceBreakerNotificationUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableLastError(v *string) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetEventPublishedAt sets the "event_published_at" field.
func (_u *SourceBreakerNotificationUpdate) SetEventPublishedAt(v time.Time) *SourceBreakerNotificationUpdate {
	_u.mutation.SetEventPublishedAt(v)
	return _u
}

// SetNillableEventPublishedAt sets the "event_published_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableEventPublishedAt(v *time.Time) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetEventPublishedAt(*v)
	}
	return _u
}

// ClearEventPublishedAt clears the value of the "event_published_at" field.
func (_u *SourceBreakerNotificationUpdate) ClearEventPublishedAt() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearEventPublishedAt()
	return _u
}

// SetHookPublishedAt sets the "hook_published_at" field.
func (_u *SourceBreakerNotificationUpdate) SetHookPublishedAt(v time.Time) *SourceBreakerNotificationUpdate {
	_u.mutation.SetHookPublishedAt(v)
	return _u
}

// SetNillableHookPublishedAt sets the "hook_published_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableHookPublishedAt(v *time.Time) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetHookPublishedAt(*v)
	}
	return _u
}

// ClearHookPublishedAt clears the value of the "hook_published_at" field.
func (_u *SourceBreakerNotificationUpdate) ClearHookPublishedAt() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearHookPublishedAt()
	return _u
}

// SetPublicationAttempts sets the "publication_attempts" field.
func (_u *SourceBreakerNotificationUpdate) SetPublicationAttempts(v int) *SourceBreakerNotificationUpdate {
	_u.mutation.ResetPublicationAttempts()
	_u.mutation.SetPublicationAttempts(v)
	return _u
}

// SetNillablePublicationAttempts sets the "publication_attempts" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillablePublicationAttempts(v *int) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetPublicationAttempts(*v)
	}
	return _u
}

// AddPublicationAttempts adds value to the "publication_attempts" field.
func (_u *SourceBreakerNotificationUpdate) AddPublicationAttempts(v int) *SourceBreakerNotificationUpdate {
	_u.mutation.AddPublicationAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *SourceBreakerNotificationUpdate) SetNextAttemptAt(v time.Time) *SourceBreakerNotificationUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillableNextAttemptAt(v *time.Time) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *SourceBreakerNotificationUpdate) ClearNextAttemptAt() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetPublicationError sets the "publication_error" field.
func (_u *SourceBreakerNotificationUpdate) SetPublicationError(v string) *SourceBreakerNotificationUpdate {
	_u.mutation.SetPublicationError(v)
	return _u
}

// SetNillablePublicationError sets the "publication_error" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillablePublicationError(v *string) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetPublicationError(*v)
	}
	return _u
}

// ClearPublicationError clears the value of the "publication_error" field.
func (_u *SourceBreakerNotificationUpdate) ClearPublicationError() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearPublicationError()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *SourceBreakerNotificationUpdate) SetPublishedAt(v time.Time) *SourceBreakerNotificationUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdate) SetNillablePublishedAt(v *time.Time) *SourceBreakerNotificationUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *SourceBreakerNotificationUpdate) ClearPublishedAt() *SourceBreakerNotificationUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the SourceBreakerNotificationMutation object of the builder.
func (_u *SourceBreakerNotificationUpdate) Mutation() *SourceBreakerNotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceBreakerNotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceBreakerNotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceBreakerNotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceBreakerNotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SourceBreakerNotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sourcebreakernotification.Table, sourcebreakernotification.Columns, sqlgraph.NewFieldSpec(sourcebreakernotification.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(sourcebreakernotification.FieldSourceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(sourcebreakernotification.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sourcebreakernotification.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(sourcebreakernotification.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(sourcebreakernotification.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCategory(); ok {
		_spec.SetField(sourcebreakernotification.FieldErrorCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventRequested(); ok {
		_spec.SetField(sourcebreakernotification.FieldEventRequested, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HookRequested(); ok {
		_spec.SetField(sourcebreakernotification.FieldHookRequested, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(sourcebreakernotification.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(sourcebreakernotification.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(sourcebreakernotification.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(sourcebreakernotification.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.FailingSince(); ok {
		_spec.SetField(sourcebreakernotification.FieldFailingSince, field.TypeTime, value)
	}
	if _u.mutation.FailingSinceCleared() {
		_spec.ClearField(sourcebreakernotification.FieldFailingSince, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(sourcebreakernotification.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventPublishedAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldEventPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.EventPublishedAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldEventPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HookPublishedAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldHookPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.HookPublishedAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldHookPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublicationAttempts(); ok {
		_spec.SetField(sourcebreakernotification.FieldPublicationAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublicationAttempts(); ok {
		_spec.AddField(sourcebreakernotification.FieldPublicationAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublicationError(); ok {
		_spec.SetField(sourcebreakernotification.FieldPublicationError, field.TypeString, value)
	}
	if _u.mutation.PublicationErrorCleared() {
		_spec.ClearField(sourcebreakernotification.FieldPublicationError, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldPublishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcebreakernotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceBreakerNotificationUpdateOne is the builder for updating a single SourceBreakerNotification entity.
type SourceBreakerNotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceBreakerNotificationMutation
}

// SetSourceKey sets the "source_key" field.
func (_u *SourceBreakerNotificationUpdateOne) SetSourceKey(v string) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableSourceKey(v *string) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *SourceBreakerNotificationUpdateOne) SetEventType(v string) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableEventType(v *string) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SourceBreakerNotificationUpdateOne) SetStatus(v string) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableStatus(v *string) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SourceBreakerNotificationUpdateOne) SetErrorMessage(v string) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableErrorMessage(v *string) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearErrorMessage() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorCategory sets the "error_category" field.
func (_u *SourceBreakerNotificationUpdateOne) SetErrorCategory(v string) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetErrorCategory(v)
	return _u
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableErrorCategory(v *string) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetErrorCategory(*v)
	}
	return _u
}

// SetEventRequested sets the "event_requested" field.
func (_u *SourceBreakerNotificationUpdateOne) SetEventRequested(v bool) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetEventRequested(v)
	return _u
}

// SetNillableEventRequested sets the "event_requested" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableEventRequested(v *bool) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetEventRequested(*v)
	}
	return _u
}

// SetHookRequested sets the "hook_requested" field.
func (_u *SourceBreakerNotificationUpdateOne) SetHookRequested(v bool) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetHookRequested(v)
	return _u
}

// SetNillableHookRequested sets the "hook_requested" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableHookRequested(v *bool) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetHookRequested(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *SourceBreakerNotificationUpdateOne) SetConsecutiveFailures(v int) *SourceBreakerNotificationUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableConsecutiveFailures(v *int) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *SourceBreakerNotificationUpdateOne) AddConsecutiveFailures(v int) *SourceBreakerNotificationUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *SourceBreakerNotificationUpdateOne) SetCooldownUntil(v time.Time) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableCooldownUntil(v *time.Time) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearCooldownUntil() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetFailingSince sets the "failing_since" field.
func (_u *SourceBreakerNotificationUpdateOne) SetFailingSince(v time.Time) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetFailingSince(v)
	return _u
}

// SetNillableFailingSince sets the "failing_since" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableFailingSince(v *time.Time) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetFailingSince(*v)
	}
	return _u
}

// ClearFailingSince clears the value of the "failing_since" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearFailingSince() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearFailingSince()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SourceBreakerNotificationUpdateOne) SetLastError(v string) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableLastError(v *string) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetEventPublishedAt sets the "event_published_at" field.
func (_u *SourceBreakerNotificationUpdateOne) SetEventPublishedAt(v time.Time) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetEventPublishedAt(v)
	return _u
}

// SetNillableEventPublishedAt sets the "event_published_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableEventPublishedAt(v *time.Time) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetEventPublishedAt(*v)
	}
	return _u
}

// ClearEventPublishedAt clears the value of the "event_published_at" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearEventPublishedAt() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearEventPublishedAt()
	return _u
}

// SetHookPublishedAt sets the "hook_published_at" field.
func (_u *SourceBreakerNotificationUpdateOne) SetHookPublishedAt(v time.Time) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetHookPublishedAt(v)
	return _u
}

// SetNillableHookPublishedAt sets the "hook_published_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableHookPublishedAt(v *time.Time) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetHookPublishedAt(*v)
	}
	return _u
}

// ClearHookPublishedAt clears the value of the "hook_published_at" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearHookPublishedAt() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearHookPublishedAt()
	return _u
}

// SetPublicationAttempts sets the "publication_attempts" field.
func (_u *SourceBreakerNotificationUpdateOne) SetPublicationAttempts(v int) *SourceBreakerNotificationUpdateOne {
	_u.mutation.ResetPublicationAttempts()
	_u.mutation.SetPublicationAttempts(v)
	return _u
}

// SetNillablePublicationAttempts sets the "publication_attempts" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillablePublicationAttempts(v *int) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetPublicationAttempts(*v)
	}
	return _u
}

// AddPublicationAttempts adds value to the "publication_attempts" field.
func (_u *SourceBreakerNotificationUpdateOne) AddPublicationAttempts(v int) *SourceBreakerNotificationUpdateOne {
	_u.mutation.AddPublicationAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *SourceBreakerNotificationUpdateOne) SetNextAttemptAt(v time.Time) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillableNextAttemptAt(v *time.Time) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearNextAttemptAt() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetPublicationError sets the "publication_error" field.
func (_u *SourceBreakerNotificationUpdateOne) SetPublicationError(v string) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetPublicationError(v)
	return _u
}

// SetNillablePublicationError sets the "publication_error" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillablePublicationError(v *string) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetPublicationError(*v)
	}
	return _u
}

// ClearPublicationError clears the value of the "publication_error" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearPublicationError() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearPublicationError()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *SourceBreakerNotificationUpdateOne) SetPublishedAt(v time.Time) *SourceBreakerNotificationUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *SourceBreakerNotificationUpdateOne) SetNillablePublishedAt(v *time.Time) *SourceBreakerNotificationUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *SourceBreakerNotificationUpdateOne) ClearPublishedAt() *SourceBreakerNotificationUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the SourceBreakerNotificationMutation object of the builder.
func (_u *SourceBreakerNotificationUpdateOne) Mutation() *SourceBreakerNotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the SourceBreakerNotificationUpdate builder.
func (_u *SourceBreakerNotificationUpdateOne) Where(ps ...predicate.SourceBreakerNotification) *SourceBreakerNotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceBreakerNotificationUpdateOne) Select(field string, fields ...string) *SourceBreakerNotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SourceBreakerNotification entity.
func (_u *SourceBreakerNotificationUpdateOne) Save(ctx context.Context) (*SourceBreakerNotification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceBreakerNotificationUpdateOne) SaveX(ctx context.Context) *SourceBreakerNotification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceBreakerNotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceBreakerNotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SourceBreakerNotificationUpdateOne) sqlSave(ctx context.Context) (_node *SourceBreakerNotification, err error) {
	_spec := sqlgraph.NewUpdateSpec(sourcebreakernotification.Table, sourcebreakernotification.Columns, sqlgraph.NewFieldSpec(sourcebreakernotification.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SourceBreakerNotification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sourcebreakernotification.FieldID)
		for _, f := range fields {
			if !sourcebreakernotification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sourcebreakernotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(sourcebreakernotification.FieldSourceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(sourcebreakernotification.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sourcebreakernotification.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(sourcebreakernotification.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(sourcebreakernotification.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCategory(); ok {
		_spec.SetField(sourcebreakernotification.FieldErrorCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventRequested(); ok {
		_spec.SetField(sourcebreakernotification.FieldEventRequested, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HookRequested(); ok {
		_spec.SetField(sourcebreakernotification.FieldHookRequested, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(sourcebreakernotification.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(sourcebreakernotification.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(sourcebreakernotification.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(sourcebreakernotification.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.FailingSince(); ok {
		_spec.SetField(sourcebreakernotification.FieldFailingSince, field.TypeTime, value)
	}
	if _u.mutation.FailingSinceCleared() {
		_spec.ClearField(sourcebreakernotification.FieldFailingSince, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(sourcebreakernotification.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventPublishedAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldEventPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.EventPublishedAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldEventPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HookPublishedAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldHookPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.HookPublishedAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldHookPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublicationAttempts(); ok {
		_spec.SetField(sourcebreakernotification.FieldPublicationAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublicationAttempts(); ok {
		_spec.AddField(sourcebreakernotification.FieldPublicationAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublicationError(); ok {
		_spec.SetField(sourcebreakernotification.FieldPublicationError, field.TypeString, value)
	}
	if _u.mutation.PublicationErrorCleared() {
		_spec.ClearField(sourcebreakernotification.FieldPublicationError, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(sourcebreakernotification.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(sourcebreakernotification.FieldPublishedAt, field.TypeTime)
	}
	_node = &SourceBreakerNotification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcebreakernotification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
