// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/sourcethroughputpolicy"
)

// SourceThroughputPolicyCreate is the builder for creating a SourceThroughputPolicy entity.
type SourceThroughputPolicyCreate struct {
	config
	mutation *SourceThroughputPolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSourceID sets the "source_id" field.
func (_c *SourceThroughputPolicyCreate) SetSourceID(v int64) *SourceThroughputPolicyCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetDownloadConcurrency sets the "download_concurrency" field.
func (_c *SourceThroughputPolicyCreate) SetDownloadConcurrency(v int) *SourceThroughputPolicyCreate {
	_c.mutation.SetDownloadConcurrency(v)
	return _c
}

// SetNillableDownloadConcurrency sets the "download_concurrency" field if the given value is not nil.
func (_c *SourceThroughputPolicyCreate) SetNillableDownloadConcurrency(v *int) *SourceThroughputPolicyCreate {
	if v != nil {
		_c.SetDownloadConcurrency(*v)
	}
	return _c
}

// SetImageRequestDelayMs sets the "image_request_delay_ms" field.
func (_c *SourceThroughputPolicyCreate) SetImageRequestDelayMs(v int64) *SourceThroughputPolicyCreate {
	_c.mutation.SetImageRequestDelayMs(v)
	return _c
}

// SetNillableImageRequestDelayMs sets the "image_request_delay_ms" field if the given value is not nil.
func (_c *SourceThroughputPolicyCreate) SetNillableImageRequestDelayMs(v *int64) *SourceThroughputPolicyCreate {
	if v != nil {
		_c.SetImageRequestDelayMs(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SourceThroughputPolicyCreate) SetCreatedAt(v time.Time) *SourceThroughputPolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SourceThroughputPolicyCreate) SetNillableCreatedAt(v *time.Time) *SourceThroughputPolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SourceThroughputPolicyCreate) SetUpdatedAt(v time.Time) *SourceThroughputPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SourceThroughputPolicyCreate) SetNillableUpdatedAt(v *time.Time) *SourceThroughputPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SourceThroughputPolicyCreate) SetID(v uuid.UUID) *SourceThroughputPolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SourceThroughputPolicyCreate) SetNillableID(v *uuid.UUID) *SourceThroughputPolicyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SourceThroughputPolicyMutation object of the builder.
func (_c *SourceThroughputPolicyCreate) Mutation() *SourceThroughputPolicyMutation {
	return _c.mutation
}

// Save creates the SourceThroughputPolicy in the database.
func (_c *SourceThroughputPolicyCreate) Save(ctx context.Context) (*SourceThroughputPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceThroughputPolicyCreate) SaveX(ctx context.Context) *SourceThroughputPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceThroughputPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceThroughputPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SourceThroughputPolicyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sourcethroughputpolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sourcethroughputpolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := sourcethroughputpolicy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceThroughputPolicyCreate) check() error {
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "SourceThroughputPolicy.source_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SourceThroughputPolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SourceThroughputPolicy.updated_at"`)}
	}
	return nil
}

func (_c *SourceThroughputPolicyCreate) sqlSave(ctx context.Context) (*SourceThroughputPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceThroughputPolicyCreate) createSpec() (*SourceThroughputPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &SourceThroughputPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sourcethroughputpolicy.Table, sqlgraph.NewFieldSpec(sourcethroughputpolicy.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldSourceID, field.TypeInt64, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.DownloadConcurrency(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldDownloadConcurrency, field.TypeInt, value)
		_node.DownloadConcurrency = &value
	}
	if value, ok := _c.mutation.ImageRequestDelayMs(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldImageRequestDelayMs, field.TypeInt64, value)
		_node.ImageRequestDelayMs = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SourceThroughputPolicy.Create().
//		SetSourceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceThroughputPolicyUpsert) {
//			SetSourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *SourceThroughputPolicyCreate) OnConflict(opts ...sql.ConflictOption) *SourceThroughputPolicyUpsertOne {
	_c.conflict = opts
	return &SourceThroughputPolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SourceThroughputPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SourceThroughputPolicyCreate) OnConflictColumns(columns ...string) *SourceThroughputPolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SourceThroughputPolicyUpsertOne{
		create: _c,
	}
}

type (
	// SourceThroughputPolicyUpsertOne is the builder for "upsert"-ing
	//  one SourceThroughputPolicy node.
	SourceThroughputPolicyUpsertOne struct {
		create *SourceThroughputPolicyCreate
	}

	// SourceThroughputPolicyUpsert is the "OnConflict" setter.
	SourceThroughputPolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetSourceID sets the "source_id" field.
func (u *SourceThroughputPolicyUpsert) SetSourceID(v int64) *SourceThroughputPolicyUpsert {
	u.Set(sourcethroughputpolicy.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsert) UpdateSourceID() *SourceThroughputPolicyUpsert {
	u.SetExcluded(sourcethroughputpolicy.FieldSourceID)
	return u
}

// AddSourceID adds v to the "source_id" field.
func (u *SourceThroughputPolicyUpsert) AddSourceID(v int64) *SourceThroughputPolicyUpsert {
	u.Add(sourcethroughputpolicy.FieldSourceID, v)
	return u
}

// SetDownloadConcurrency sets the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsert) SetDownloadConcurrency(v int) *SourceThroughputPolicyUpsert {
	u.Set(sourcethroughputpolicy.FieldDownloadConcurrency, v)
	return u
}

// UpdateDownloadConcurrency sets the "download_concurrency" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsert) UpdateDownloadConcurrency() *SourceThroughputPolicyUpsert {
	u.SetExcluded(sourcethroughputpolicy.FieldDownloadConcurrency)
	return u
}

// AddDownloadConcurrency adds v to the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsert) AddDownloadConcurrency(v int) *SourceThroughputPolicyUpsert {
	u.Add(sourcethroughputpolicy.FieldDownloadConcurrency, v)
	return u
}

// ClearDownloadConcurrency clears the value of the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsert) ClearDownloadConcurrency() *SourceThroughputPolicyUpsert {
	u.SetNull(sourcethroughputpolicy.FieldDownloadConcurrency)
	return u
}

// SetImageRequestDelayMs sets the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsert) SetImageRequestDelayMs(v int64) *SourceThroughputPolicyUpsert {
	u.Set(sourcethroughputpolicy.FieldImageRequestDelayMs, v)
	return u
}

// UpdateImageRequestDelayMs sets the "image_request_delay_ms" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsert) UpdateImageRequestDelayMs() *SourceThroughputPolicyUpsert {
	u.SetExcluded(sourcethroughputpolicy.FieldImageRequestDelayMs)
	return u
}

// AddImageRequestDelayMs adds v to the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsert) AddImageRequestDelayMs(v int64) *SourceThroughputPolicyUpsert {
	u.Add(sourcethroughputpolicy.FieldImageRequestDelayMs, v)
	return u
}

// ClearImageRequestDelayMs clears the value of the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsert) ClearImageRequestDelayMs() *SourceThroughputPolicyUpsert {
	u.SetNull(sourcethroughputpolicy.FieldImageRequestDelayMs)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SourceThroughputPolicyUpsert) SetUpdatedAt(v time.Time) *SourceThroughputPolicyUpsert {
	u.Set(sourcethroughputpolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsert) UpdateUpdatedAt() *SourceThroughputPolicyUpsert {
	u.SetExcluded(sourcethroughputpolicy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SourceThroughputPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sourcethroughputpolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SourceThroughputPolicyUpsertOne) UpdateNewValues() *SourceThroughputPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(sourcethroughputpolicy.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sourcethroughputpolicy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SourceThroughputPolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SourceThroughputPolicyUpsertOne) Ignore() *SourceThroughputPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceThroughputPolicyUpsertOne) DoNothing() *SourceThroughputPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceThroughputPolicyCreate.OnConflict
// documentation for more info.
func (u *SourceThroughputPolicyUpsertOne) Update(set func(*SourceThroughputPolicyUpsert)) *SourceThroughputPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceThroughputPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceID sets the "source_id" field.
func (u *SourceThroughputPolicyUpsertOne) SetSourceID(v int64) *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *SourceThroughputPolicyUpsertOne) AddSourceID(v int64) *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertOne) UpdateSourceID() *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateSourceID()
	})
}

// SetDownloadConcurrency sets the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsertOne) SetDownloadConcurrency(v int) *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetDownloadConcurrency(v)
	})
}

// AddDownloadConcurrency adds v to the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsertOne) AddDownloadConcurrency(v int) *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.AddDownloadConcurrency(v)
	})
}

// UpdateDownloadConcurrency sets the "download_concurrency" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertOne) UpdateDownloadConcurrency() *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateDownloadConcurrency()
	})
}

// ClearDownloadConcurrency clears the value of the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsertOne) ClearDownloadConcurrency() *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.ClearDownloadConcurrency()
	})
}

// SetImageRequestDelayMs sets the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsertOne) SetImageRequestDelayMs(v int64) *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetImageRequestDelayMs(v)
	})
}

// AddImageRequestDelayMs adds v to the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsertOne) AddImageRequestDelayMs(v int64) *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.AddImageRequestDelayMs(v)
	})
}

// UpdateImageRequestDelayMs sets the "image_request_delay_ms" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertOne) UpdateImageRequestDelayMs() *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateImageRequestDelayMs()
	})
}

// ClearImageRequestDelayMs clears the value of the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsertOne) ClearImageRequestDelayMs() *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.ClearImageRequestDelayMs()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SourceThroughputPolicyUpsertOne) SetUpdatedAt(v time.Time) *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertOne) UpdateUpdatedAt() *SourceThroughputPolicyUpsertOne {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SourceThroughputPolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SourceThroughputPolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceThroughputPolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SourceThroughputPolicyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SourceThroughputPolicyUpsertOne.ID is not supported by MySQL driver. Use SourceThroughputPolicyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SourceThroughputPolicyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SourceThroughputPolicyCreateBulk is the builder for creating many SourceThroughputPolicy entities in bulk.
type SourceThroughputPolicyCreateBulk struct {
	config
	err      error
	builders []*SourceThroughputPolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the SourceThroughputPolicy entities in the database.
func (_c *SourceThroughputPolicyCreateBulk) Save(ctx context.Context) ([]*SourceThroughputPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SourceThroughputPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceThroughputPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceThroughputPolicyCreateBulk) SaveX(ctx context.Context) []*SourceThroughputPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceThroughputPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceThroughputPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SourceThroughputPolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceThroughputPolicyUpsert) {
//			SetSourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *SourceThroughputPolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *SourceThroughputPolicyUpsertBulk {
	_c.conflict = opts
	return &SourceThroughputPolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SourceThroughputPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SourceThroughputPolicyCreateBulk) OnConflictColumns(columns ...string) *SourceThroughputPolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SourceThroughputPolicyUpsertBulk{
		create: _c,
	}
}

// SourceThroughputPolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of SourceThroughputPolicy nodes.
type SourceThroughputPolicyUpsertBulk struct {
	create *SourceThroughputPolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SourceThroughputPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sourcethroughputpolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SourceThroughputPolicyUpsertBulk) UpdateNewValues() *SourceThroughputPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(sourcethroughputpolicy.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sourcethroughputpolicy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SourceThroughputPolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SourceThroughputPolicyUpsertBulk) Ignore() *SourceThroughputPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceThroughputPolicyUpsertBulk) DoNothing() *SourceThroughputPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceThroughputPolicyCreateBulk.OnConflict
// documentation for more info.
func (u *SourceThroughputPolicyUpsertBulk) Update(set func(*SourceThroughputPolicyUpsert)) *SourceThroughputPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceThroughputPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceID sets the "source_id" field.
func (u *SourceThroughputPolicyUpsertBulk) SetSourceID(v int64) *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *SourceThroughputPolicyUpsertBulk) AddSourceID(v int64) *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertBulk) UpdateSourceID() *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateSourceID()
	})
}

// SetDownloadConcurrency sets the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsertBulk) SetDownloadConcurrency(v int) *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetDownloadConcurrency(v)
	})
}

// AddDownloadConcurrency adds v to the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsertBulk) AddDownloadConcurrency(v int) *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.AddDownloadConcurrency(v)
	})
}

// UpdateDownloadConcurrency sets the "download_concurrency" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertBulk) UpdateDownloadConcurrency() *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateDownloadConcurrency()
	})
}

// ClearDownloadConcurrency clears the value of the "download_concurrency" field.
func (u *SourceThroughputPolicyUpsertBulk) ClearDownloadConcurrency() *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.ClearDownloadConcurrency()
	})
}

// SetImageRequestDelayMs sets the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsertBulk) SetImageRequestDelayMs(v int64) *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetImageRequestDelayMs(v)
	})
}

// AddImageRequestDelayMs adds v to the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsertBulk) AddImageRequestDelayMs(v int64) *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.AddImageRequestDelayMs(v)
	})
}

// UpdateImageRequestDelayMs sets the "image_request_delay_ms" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertBulk) UpdateImageRequestDelayMs() *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateImageRequestDelayMs()
	})
}

// ClearImageRequestDelayMs clears the value of the "image_request_delay_ms" field.
func (u *SourceThroughputPolicyUpsertBulk) ClearImageRequestDelayMs() *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.ClearImageRequestDelayMs()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SourceThroughputPolicyUpsertBulk) SetUpdatedAt(v time.Time) *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SourceThroughputPolicyUpsertBulk) UpdateUpdatedAt() *SourceThroughputPolicyUpsertBulk {
	return u.Update(func(s *SourceThroughputPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SourceThroughputPolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SourceThroughputPolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SourceThroughputPolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceThroughputPolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
