// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
	"github.com/technobecet/tsundoku/internal/ent/sourcethroughputpolicy"
)

// SourceThroughputPolicyUpdate is the builder for updating SourceThroughputPolicy entities.
type SourceThroughputPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *SourceThroughputPolicyMutation
}

// Where appends a list predicates to the SourceThroughputPolicyUpdate builder.
func (_u *SourceThroughputPolicyUpdate) Where(ps ...predicate.SourceThroughputPolicy) *SourceThroughputPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *SourceThroughputPolicyUpdate) SetSourceID(v int64) *SourceThroughputPolicyUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *SourceThroughputPolicyUpdate) SetNillableSourceID(v *int64) *SourceThroughputPolicyUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *SourceThroughputPolicyUpdate) AddSourceID(v int64) *SourceThroughputPolicyUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetDownloadConcurrency sets the "download_concurrency" field.
func (_u *SourceThroughputPolicyUpdate) SetDownloadConcurrency(v int) *SourceThroughputPolicyUpdate {
	_u.mutation.ResetDownloadConcurrency()
	_u.mutation.SetDownloadConcurrency(v)
	return _u
}

// SetNillableDownloadConcurrency sets the "download_concurrency" field if the given value is not nil.
func (_u *SourceThroughputPolicyUpdate) SetNillableDownloadConcurrency(v *int) *SourceThroughputPolicyUpdate {
	if v != nil {
		_u.SetDownloadConcurrency(*v)
	}
	return _u
}

// AddDownloadConcurrency adds value to the "download_concurrency" field.
func (_u *SourceThroughputPolicyUpdate) AddDownloadConcurrency(v int) *SourceThroughputPolicyUpdate {
	_u.mutation.AddDownloadConcurrency(v)
	return _u
}

// ClearDownloadConcurrency clears the value of the "download_concurrency" field.
func (_u *SourceThroughputPolicyUpdate) ClearDownloadConcurrency() *SourceThroughputPolicyUpdate {
	_u.mutation.ClearDownloadConcurrency()
	return _u
}

// SetImageRequestDelayMs sets the "image_request_delay_ms" field.
func (_u *SourceThroughputPolicyUpdate) SetImageRequestDelayMs(v int64) *SourceThroughputPolicyUpdate {
	_u.mutation.ResetImageRequestDelayMs()
	_u.mutation.SetImageRequestDelayMs(v)
	return _u
}

// SetNillableImageRequestDelayMs sets the "image_request_delay_ms" field if the given value is not nil.
func (_u *SourceThroughputPolicyUpdate) SetNillableImageRequestDelayMs(v *int64) *SourceThroughputPolicyUpdate {
	if v != nil {
		_u.SetImageRequestDelayMs(*v)
	}
	return _u
}

// AddImageRequestDelayMs adds value to the "image_request_delay_ms" field.
func (_u *SourceThroughputPolicyUpdate) AddImageRequestDelayMs(v int64) *SourceThroughputPolicyUpdate {
	_u.mutation.AddImageRequestDelayMs(v)
	return _u
}

// ClearImageRequestDelayMs clears the value of the "image_request_delay_ms" field.
func (_u *SourceThroughputPolicyUpdate) ClearImageRequestDelayMs() *SourceThroughputPolicyUpdate {
	_u.mutation.ClearImageRequestDelayMs()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceThroughputPolicyUpdate) SetUpdatedAt(v time.Time) *SourceThroughputPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SourceThroughputPolicyMutation object of the builder.
func (_u *SourceThroughputPolicyUpdate) Mutation() *SourceThroughputPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceThroughputPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceThroughputPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceThroughputPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceThroughputPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceThroughputPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sourcethroughputpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SourceThroughputPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sourcethroughputpolicy.Table, sourcethroughputpolicy.Columns, sqlgraph.NewFieldSpec(sourcethroughputpolicy.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(sourcethroughputpolicy.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DownloadConcurrency(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldDownloadConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadConcurrency(); ok {
		_spec.AddField(sourcethroughputpolicy.FieldDownloadConcurrency, field.TypeInt, value)
	}
	if _u.mutation.DownloadConcurrencyCleared() {
		_spec.ClearField(sourcethroughputpolicy.FieldDownloadConcurrency, field.TypeInt)
	}
	if value, ok := _u.mutation.ImageRequestDelayMs(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldImageRequestDelayMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageRequestDelayMs(); ok {
		_spec.AddField(sourcethroughputpolicy.FieldImageRequestDelayMs, field.TypeInt64, value)
	}
	if _u.mutation.ImageRequestDelayMsCleared() {
		_spec.ClearField(sourcethroughputpolicy.FieldImageRequestDelayMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcethroughputpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceThroughputPolicyUpdateOne is the builder for updating a single SourceThroughputPolicy entity.
type SourceThroughputPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceThroughputPolicyMutation
}

// SetSourceID sets the "source_id" field.
func (_u *SourceThroughputPolicyUpdateOne) SetSourceID(v int64) *SourceThroughputPolicyUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *SourceThroughputPolicyUpdateOne) SetNillableSourceID(v *int64) *SourceThroughputPolicyUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *SourceThroughputPolicyUpdateOne) AddSourceID(v int64) *SourceThroughputPolicyUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetDownloadConcurrency sets the "download_concurrency" field.
func (_u *SourceThroughputPolicyUpdateOne) SetDownloadConcurrency(v int) *SourceThroughputPolicyUpdateOne {
	_u.mutation.ResetDownloadConcurrency()
	_u.mutation.SetDownloadConcurrency(v)
	return _u
}

// SetNillableDownloadConcurrency sets the "download_concurrency" field if the given value is not nil.
func (_u *SourceThroughputPolicyUpdateOne) SetNillableDownloadConcurrency(v *int) *SourceThroughputPolicyUpdateOne {
	if v != nil {
		_u.SetDownloadConcurrency(*v)
	}
	return _u
}

// AddDownloadConcurrency adds value to the "download_concurrency" field.
func (_u *SourceThroughputPolicyUpdateOne) AddDownloadConcurrency(v int) *SourceThroughputPolicyUpdateOne {
	_u.mutation.AddDownloadConcurrency(v)
	return _u
}

// ClearDownloadConcurrency clears the value of the "download_concurrency" field.
func (_u *SourceThroughputPolicyUpdateOne) ClearDownloadConcurrency() *SourceThroughputPolicyUpdateOne {
	_u.mutation.ClearDownloadConcurrency()
	return _u
}

// SetImageRequestDelayMs sets the "image_request_delay_ms" field.
func (_u *SourceThroughputPolicyUpdateOne) SetImageRequestDelayMs(v int64) *SourceThroughputPolicyUpdateOne {
	_u.mutation.ResetImageRequestDelayMs()
	_u.mutation.SetImageRequestDelayMs(v)
	return _u
}

// SetNillableImageRequestDelayMs sets the "image_request_delay_ms" field if the given value is not nil.
func (_u *SourceThroughputPolicyUpdateOne) SetNillableImageRequestDelayMs(v *int64) *SourceThroughputPolicyUpdateOne {
	if v != nil {
		_u.SetImageRequestDelayMs(*v)
	}
	return _u
}

// AddImageRequestDelayMs adds value to the "image_request_delay_ms" field.
func (_u *SourceThroughputPolicyUpdateOne) AddImageRequestDelayMs(v int64) *SourceThroughputPolicyUpdateOne {
	_u.mutation.AddImageRequestDelayMs(v)
	return _u
}

// ClearImageRequestDelayMs clears the value of the "image_request_delay_ms" field.
func (_u *SourceThroughputPolicyUpdateOne) ClearImageRequestDelayMs() *SourceThroughputPolicyUpdateOne {
	_u.mutation.ClearImageRequestDelayMs()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceThroughputPolicyUpdateOne) SetUpdatedAt(v time.Time) *SourceThroughputPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SourceThroughputPolicyMutation object of the builder.
func (_u *SourceThroughputPolicyUpdateOne) Mutation() *SourceThroughputPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the SourceThroughputPolicyUpdate builder.
func (_u *SourceThroughputPolicyUpdateOne) Where(ps ...predicate.SourceThroughputPolicy) *SourceThroughputPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceThroughputPolicyUpdateOne) Select(field string, fields ...string) *SourceThroughputPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SourceThroughputPolicy entity.
func (_u *SourceThroughputPolicyUpdateOne) Save(ctx context.Context) (*SourceThroughputPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceThroughputPolicyUpdateOne) SaveX(ctx context.Context) *SourceThroughputPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceThroughputPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceThroughputPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceThroughputPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sourcethroughputpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SourceThroughputPolicyUpdateOne) sqlSave(ctx context.Context) (_node *SourceThroughputPolicy, err error) {
	_spec := sqlgraph.NewUpdateSpec(sourcethroughputpolicy.Table, sourcethroughputpolicy.Columns, sqlgraph.NewFieldSpec(sourcethroughputpolicy.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SourceThroughputPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sourcethroughputpolicy.FieldID)
		for _, f := range fields {
			if !sourcethroughputpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sourcethroughputpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(sourcethroughputpolicy.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DownloadConcurrency(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldDownloadConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadConcurrency(); ok {
		_spec.AddField(sourcethroughputpolicy.FieldDownloadConcurrency, field.TypeInt, value)
	}
	if _u.mutation.DownloadConcurrencyCleared() {
		_spec.ClearField(sourcethroughputpolicy.FieldDownloadConcurrency, field.TypeInt)
	}
	if value, ok := _u.mutation.ImageRequestDelayMs(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldImageRequestDelayMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageRequestDelayMs(); ok {
		_spec.AddField(sourcethroughputpolicy.FieldImageRequestDelayMs, field.TypeInt64, value)
	}
	if _u.mutation.ImageRequestDelayMsCleared() {
		_spec.ClearField(sourcethroughputpolicy.FieldImageRequestDelayMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sourcethroughputpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SourceThroughputPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcethroughputpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
