// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/sourceevent"
)

// SourceEvent is the model entity for the SourceEvent schema.
type SourceEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SourceKey holds the value of the "source_key" field.
	SourceKey string `json:"source_key,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// SourceName holds the value of the "source_name" field.
	SourceName string `json:"source_name,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType sourceevent.EventType `json:"event_type,omitempty"`
	// Status holds the value of the "status" field.
	Status sourceevent.Status `json:"status,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// ErrorCategory holds the value of the "error_category" field.
	ErrorCategory *string `json:"error_category,omitempty"`
	// ItemsCount holds the value of the "items_count" field.
	ItemsCount *int `json:"items_count,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SourceEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sourceevent.FieldMetadata:
			values[i] = new([]byte)
		case sourceevent.FieldDurationMs, sourceevent.FieldItemsCount:
			values[i] = new(sql.NullInt64)
		case sourceevent.FieldSourceKey, sourceevent.FieldSourceID, sourceevent.FieldSourceName, sourceevent.FieldLanguage, sourceevent.FieldEventType, sourceevent.FieldStatus, sourceevent.FieldErrorMessage, sourceevent.FieldErrorCategory:
			values[i] = new(sql.NullString)
		case sourceevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case sourceevent.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SourceEvent fields.
func (_m *SourceEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sourceevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case sourceevent.FieldSourceKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_key", values[i])
			} else if value.Valid {
				_m.SourceKey = value.String
			}
		case sourceevent.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case sourceevent.FieldSourceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_name", values[i])
			} else if value.Valid {
				_m.SourceName = value.String
			}
		case sourceevent.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case sourceevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = sourceevent.EventType(value.String)
			}
		case sourceevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sourceevent.Status(value.String)
			}
		case sourceevent.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		case sourceevent.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case sourceevent.FieldErrorCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_category", values[i])
			} else if value.Valid {
				_m.ErrorCategory = new(string)
				*_m.ErrorCategory = value.String
			}
		case sourceevent.FieldItemsCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field items_count", values[i])
			} else if value.Valid {
				_m.ItemsCount = new(int)
				*_m.ItemsCount = int(value.Int64)
			}
		case sourceevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case sourceevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SourceEvent.
// This includes values selected through modifiers, order, etc.
func (_m *SourceEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SourceEvent.
// Note that you need to call SourceEvent.Unwrap() before calling this method if this SourceEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SourceEvent) Update() *SourceEventUpdateOne {
	return NewSourceEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SourceEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SourceEvent) Unwrap() *SourceEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SourceEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SourceEvent) String() string {
	var builder strings.Builder
	builder.WriteString("SourceEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_key=")
	builder.WriteString(_m.SourceKey)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("source_name=")
	builder.WriteString(_m.SourceName)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorCategory; v != nil {
		builder.WriteString("error_category=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ItemsCount; v != nil {
		builder.WriteString("items_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SourceEvents is a parsable slice of SourceEvent.
type SourceEvents []*SourceEvent
