// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/series"
	"github.com/technobecet/tsundoku/internal/ent/trackbinding"
)

// TrackBindingCreate is the builder for creating a TrackBinding entity.
type TrackBindingCreate struct {
	config
	mutation *TrackBindingMutation
	hooks    []Hook
}

// SetSeriesID sets the "series_id" field.
func (_c *TrackBindingCreate) SetSeriesID(v uuid.UUID) *TrackBindingCreate {
	_c.mutation.SetSeriesID(v)
	return _c
}

// SetTrackerID sets the "tracker_id" field.
func (_c *TrackBindingCreate) SetTrackerID(v int) *TrackBindingCreate {
	_c.mutation.SetTrackerID(v)
	return _c
}

// SetRemoteID sets the "remote_id" field.
func (_c *TrackBindingCreate) SetRemoteID(v string) *TrackBindingCreate {
	_c.mutation.SetRemoteID(v)
	return _c
}

// SetRemoteURL sets the "remote_url" field.
func (_c *TrackBindingCreate) SetRemoteURL(v string) *TrackBindingCreate {
	_c.mutation.SetRemoteURL(v)
	return _c
}

// SetNillableRemoteURL sets the "remote_url" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableRemoteURL(v *string) *TrackBindingCreate {
	if v != nil {
		_c.SetRemoteURL(*v)
	}
	return _c
}

// SetLibraryID sets the "library_id" field.
func (_c *TrackBindingCreate) SetLibraryID(v string) *TrackBindingCreate {
	_c.mutation.SetLibraryID(v)
	return _c
}

// SetNillableLibraryID sets the "library_id" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableLibraryID(v *string) *TrackBindingCreate {
	if v != nil {
		_c.SetLibraryID(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *TrackBindingCreate) SetTitle(v string) *TrackBindingCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableTitle(v *string) *TrackBindingCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TrackBindingCreate) SetStatus(v string) *TrackBindingCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableStatus(v *string) *TrackBindingCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastChapterRead sets the "last_chapter_read" field.
func (_c *TrackBindingCreate) SetLastChapterRead(v float64) *TrackBindingCreate {
	_c.mutation.SetLastChapterRead(v)
	return _c
}

// SetNillableLastChapterRead sets the "last_chapter_read" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableLastChapterRead(v *float64) *TrackBindingCreate {
	if v != nil {
		_c.SetLastChapterRead(*v)
	}
	return _c
}

// SetTotalChapters sets the "total_chapters" field.
func (_c *TrackBindingCreate) SetTotalChapters(v int) *TrackBindingCreate {
	_c.mutation.SetTotalChapters(v)
	return _c
}

// SetNillableTotalChapters sets the "total_chapters" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableTotalChapters(v *int) *TrackBindingCreate {
	if v != nil {
		_c.SetTotalChapters(*v)
	}
	return _c
}

// SetScore sets the "score" field.
func (_c *TrackBindingCreate) SetScore(v float64) *TrackBindingCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableScore(v *float64) *TrackBindingCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *TrackBindingCreate) SetStartDate(v time.Time) *TrackBindingCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableStartDate(v *time.Time) *TrackBindingCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetFinishDate sets the "finish_date" field.
func (_c *TrackBindingCreate) SetFinishDate(v time.Time) *TrackBindingCreate {
	_c.mutation.SetFinishDate(v)
	return _c
}

// SetNillableFinishDate sets the "finish_date" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableFinishDate(v *time.Time) *TrackBindingCreate {
	if v != nil {
		_c.SetFinishDate(*v)
	}
	return _c
}

// SetPrivate sets the "private" field.
func (_c *TrackBindingCreate) SetPrivate(v bool) *TrackBindingCreate {
	_c.mutation.SetPrivate(v)
	return _c
}

// SetNillablePrivate sets the "private" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillablePrivate(v *bool) *TrackBindingCreate {
	if v != nil {
		_c.SetPrivate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TrackBindingCreate) SetCreatedAt(v time.Time) *TrackBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableCreatedAt(v *time.Time) *TrackBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TrackBindingCreate) SetUpdatedAt(v time.Time) *TrackBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableUpdatedAt(v *time.Time) *TrackBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TrackBindingCreate) SetID(v uuid.UUID) *TrackBindingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TrackBindingCreate) SetNillableID(v *uuid.UUID) *TrackBindingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSeries sets the "series" edge to the Series entity.
func (_c *TrackBindingCreate) SetSeries(v *Series) *TrackBindingCreate {
	return _c.SetSeriesID(v.ID)
}

// Mutation returns the TrackBindingMutation object of the builder.
func (_c *TrackBindingCreate) Mutation() *TrackBindingMutation {
	return _c.mutation
}

// Save creates the TrackBinding in the database.
func (_c *TrackBindingCreate) Save(ctx context.Context) (*TrackBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TrackBindingCreate) SaveX(ctx context.Context) *TrackBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrackBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrackBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TrackBindingCreate) defaults() {
	if _, ok := _c.mutation.RemoteURL(); !ok {
		v := trackbinding.DefaultRemoteURL
		_c.mutation.SetRemoteURL(v)
	}
	if _, ok := _c.mutation.LibraryID(); !ok {
		v := trackbinding.DefaultLibraryID
		_c.mutation.SetLibraryID(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := trackbinding.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := trackbinding.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.LastChapterRead(); !ok {
		v := trackbinding.DefaultLastChapterRead
		_c.mutation.SetLastChapterRead(v)
	}
	if _, ok := _c.mutation.TotalChapters(); !ok {
		v := trackbinding.DefaultTotalChapters
		_c.mutation.SetTotalChapters(v)
	}
	if _, ok := _c.mutation.Score(); !ok {
		v := trackbinding.DefaultScore
		_c.mutation.SetScore(v)
	}
	if _, ok := _c.mutation.Private(); !ok {
		v := trackbinding.DefaultPrivate
		_c.mutation.SetPrivate(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := trackbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := trackbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := trackbinding.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TrackBindingCreate) check() error {
	if _, ok := _c.mutation.SeriesID(); !ok {
		return &ValidationError{Name: "series_id", err: errors.New(`ent: missing required field "TrackBinding.series_id"`)}
	}
	if _, ok := _c.mutation.TrackerID(); !ok {
		return &ValidationError{Name: "tracker_id", err: errors.New(`ent: missing required field "TrackBinding.tracker_id"`)}
	}
	if _, ok := _c.mutation.RemoteID(); !ok {
		return &ValidationError{Name: "remote_id", err: errors.New(`ent: missing required field "TrackBinding.remote_id"`)}
	}
	if _, ok := _c.mutation.RemoteURL(); !ok {
		return &ValidationError{Name: "remote_url", err: errors.New(`ent: missing required field "TrackBinding.remote_url"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "TrackBinding.title"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TrackBinding.status"`)}
	}
	if _, ok := _c.mutation.LastChapterRead(); !ok {
		return &ValidationError{Name: "last_chapter_read", err: errors.New(`ent: missing required field "TrackBinding.last_chapter_read"`)}
	}
	if _, ok := _c.mutation.TotalChapters(); !ok {
		return &ValidationError{Name: "total_chapters", err: errors.New(`ent: missing required field "TrackBinding.total_chapters"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "TrackBinding.score"`)}
	}
	if _, ok := _c.mutation.Private(); !ok {
		return &ValidationError{Name: "private", err: errors.New(`ent: missing required field "TrackBinding.private"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TrackBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TrackBinding.updated_at"`)}
	}
	if len(_c.mutation.SeriesIDs()) == 0 {
		return &ValidationError{Name: "series", err: errors.New(`ent: missing required edge "TrackBinding.series"`)}
	}
	return nil
}

func (_c *TrackBindingCreate) sqlSave(ctx context.Context) (*TrackBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TrackBindingCreate) createSpec() (*TrackBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &TrackBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(trackbinding.Table, sqlgraph.NewFieldSpec(trackbinding.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TrackerID(); ok {
		_spec.SetField(trackbinding.FieldTrackerID, field.TypeInt, value)
		_node.TrackerID = value
	}
	if value, ok := _c.mutation.RemoteID(); ok {
		_spec.SetField(trackbinding.FieldRemoteID, field.TypeString, value)
		_node.RemoteID = value
	}
	if value, ok := _c.mutation.RemoteURL(); ok {
		_spec.SetField(trackbinding.FieldRemoteURL, field.TypeString, value)
		_node.RemoteURL = value
	}
	if value, ok := _c.mutation.LibraryID(); ok {
		_spec.SetField(trackbinding.FieldLibraryID, field.TypeString, value)
		_node.LibraryID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(trackbinding.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(trackbinding.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastChapterRead(); ok {
		_spec.SetField(trackbinding.FieldLastChapterRead, field.TypeFloat64, value)
		_node.LastChapterRead = value
	}
	if value, ok := _c.mutation.TotalChapters(); ok {
		_spec.SetField(trackbinding.FieldTotalChapters, field.TypeInt, value)
		_node.TotalChapters = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(trackbinding.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(trackbinding.FieldStartDate, field.TypeTime, value)
		_node.StartDate = &value
	}
	if value, ok := _c.mutation.FinishDate(); ok {
		_spec.SetField(trackbinding.FieldFinishDate, field.TypeTime, value)
		_node.FinishDate = &value
	}
	if value, ok := _c.mutation.Private(); ok {
		_spec.SetField(trackbinding.FieldPrivate, field.TypeBool, value)
		_node.Private = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(trackbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(trackbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   trackbinding.SeriesTable,
			Columns: []string{trackbinding.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeriesID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TrackBindingCreateBulk is the builder for creating many TrackBinding entities in bulk.
type TrackBindingCreateBulk struct {
	config
	err      error
	builders []*TrackBindingCreate
}

// Save creates the TrackBinding entities in the database.
func (_c *TrackBindingCreateBulk) Save(ctx context.Context) ([]*TrackBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TrackBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrackBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TrackBindingCreateBulk) SaveX(ctx context.Context) []*TrackBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrackBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrackBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
