// Code generated by ent, DO NOT EDIT.

package ignorescanlatorsource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldEQ(FieldSourceID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldEQ(FieldCreatedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldLTE(FieldSourceID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IgnoreScanlatorSource) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IgnoreScanlatorSource) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IgnoreScanlatorSource) predicate.IgnoreScanlatorSource {
	return predicate.IgnoreScanlatorSource(sql.NotPredicates(p))
}
