// Code generated by ent, DO NOT EDIT.

package etagcache

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLTE(FieldID, id))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldURL, v))
}

// Etag applies equality check predicate on the "etag" field. It's identical to EtagEQ.
func Etag(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldEtag, v))
}

// LastModified applies equality check predicate on the "last_modified" field. It's identical to LastModifiedEQ.
func LastModified(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldLastModified, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldUpdatedAt, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldContainsFold(FieldURL, v))
}

// EtagEQ applies the EQ predicate on the "etag" field.
func EtagEQ(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldEtag, v))
}

// EtagNEQ applies the NEQ predicate on the "etag" field.
func EtagNEQ(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNEQ(FieldEtag, v))
}

// EtagIn applies the In predicate on the "etag" field.
func EtagIn(vs ...string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldIn(FieldEtag, vs...))
}

// EtagNotIn applies the NotIn predicate on the "etag" field.
func EtagNotIn(vs ...string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNotIn(FieldEtag, vs...))
}

// EtagGT applies the GT predicate on the "etag" field.
func EtagGT(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGT(FieldEtag, v))
}

// EtagGTE applies the GTE predicate on the "etag" field.
func EtagGTE(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGTE(FieldEtag, v))
}

// EtagLT applies the LT predicate on the "etag" field.
func EtagLT(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLT(FieldEtag, v))
}

// EtagLTE applies the LTE predicate on the "etag" field.
func EtagLTE(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLTE(FieldEtag, v))
}

// EtagContains applies the Contains predicate on the "etag" field.
func EtagContains(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldContains(FieldEtag, v))
}

// EtagHasPrefix applies the HasPrefix predicate on the "etag" field.
func EtagHasPrefix(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldHasPrefix(FieldEtag, v))
}

// EtagHasSuffix applies the HasSuffix predicate on the "etag" field.
func EtagHasSuffix(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldHasSuffix(FieldEtag, v))
}

// EtagEqualFold applies the EqualFold predicate on the "etag" field.
func EtagEqualFold(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEqualFold(FieldEtag, v))
}

// EtagContainsFold applies the ContainsFold predicate on the "etag" field.
func EtagContainsFold(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldContainsFold(FieldEtag, v))
}

// LastModifiedEQ applies the EQ predicate on the "last_modified" field.
func LastModifiedEQ(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldLastModified, v))
}

// LastModifiedNEQ applies the NEQ predicate on the "last_modified" field.
func LastModifiedNEQ(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNEQ(FieldLastModified, v))
}

// LastModifiedIn applies the In predicate on the "last_modified" field.
func LastModifiedIn(vs ...string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldIn(FieldLastModified, vs...))
}

// LastModifiedNotIn applies the NotIn predicate on the "last_modified" field.
func LastModifiedNotIn(vs ...string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNotIn(FieldLastModified, vs...))
}

// LastModifiedGT applies the GT predicate on the "last_modified" field.
func LastModifiedGT(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGT(FieldLastModified, v))
}

// LastModifiedGTE applies the GTE predicate on the "last_modified" field.
func LastModifiedGTE(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGTE(FieldLastModified, v))
}

// LastModifiedLT applies the LT predicate on the "last_modified" field.
func LastModifiedLT(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLT(FieldLastModified, v))
}

// LastModifiedLTE applies the LTE predicate on the "last_modified" field.
func LastModifiedLTE(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLTE(FieldLastModified, v))
}

// LastModifiedContains applies the Contains predicate on the "last_modified" field.
func LastModifiedContains(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldContains(FieldLastModified, v))
}

// LastModifiedHasPrefix applies the HasPrefix predicate on the "last_modified" field.
func LastModifiedHasPrefix(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldHasPrefix(FieldLastModified, v))
}

// LastModifiedHasSuffix applies the HasSuffix predicate on the "last_modified" field.
func LastModifiedHasSuffix(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldHasSuffix(FieldLastModified, v))
}

// LastModifiedEqualFold applies the EqualFold predicate on the "last_modified" field.
func LastModifiedEqualFold(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEqualFold(FieldLastModified, v))
}

// LastModifiedContainsFold applies the ContainsFold predicate on the "last_modified" field.
func LastModifiedContainsFold(v string) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldContainsFold(FieldLastModified, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EtagCache {
	return predicate.EtagCache(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EtagCache) predicate.EtagCache {
	return predicate.EtagCache(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EtagCache) predicate.EtagCache {
	return predicate.EtagCache(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EtagCache) predicate.EtagCache {
	return predicate.EtagCache(sql.NotPredicates(p))
}
