// Code generated by ent, DO NOT EDIT.

package chapter

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the chapter type in the database.
	Label = "chapter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeriesID holds the string denoting the series_id field in the database.
	FieldSeriesID = "series_id"
	// FieldChapterKey holds the string denoting the chapter_key field in the database.
	FieldChapterKey = "chapter_key"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldSatisfiedByProviderID holds the string denoting the satisfied_by_provider_id field in the database.
	FieldSatisfiedByProviderID = "satisfied_by_provider_id"
	// FieldSatisfiedImportance holds the string denoting the satisfied_importance field in the database.
	FieldSatisfiedImportance = "satisfied_importance"
	// FieldPageCount holds the string denoting the page_count field in the database.
	FieldPageCount = "page_count"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldDownloadDate holds the string denoting the download_date field in the database.
	FieldDownloadDate = "download_date"
	// FieldFirstDownloadedAt holds the string denoting the first_downloaded_at field in the database.
	FieldFirstDownloadedAt = "first_downloaded_at"
	// FieldRetries holds the string denoting the retries field in the database.
	FieldRetries = "retries"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldErrorCategory holds the string denoting the error_category field in the database.
	FieldErrorCategory = "error_category"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldLastReadPage holds the string denoting the last_read_page field in the database.
	FieldLastReadPage = "last_read_page"
	// FieldReadAt holds the string denoting the read_at field in the database.
	FieldReadAt = "read_at"
	// EdgeSeries holds the string denoting the series edge name in mutations.
	EdgeSeries = "series"
	// EdgeSatisfiedBy holds the string denoting the satisfied_by edge name in mutations.
	EdgeSatisfiedBy = "satisfied_by"
	// Table holds the table name of the chapter in the database.
	Table = "chapters"
	// SeriesTable is the table that holds the series relation/edge.
	SeriesTable = "chapters"
	// SeriesInverseTable is the table name for the Series entity.
	// It exists in this package in order to avoid circular dependency with the "series" package.
	SeriesInverseTable = "series"
	// SeriesColumn is the table column denoting the series relation/edge.
	SeriesColumn = "series_id"
	// SatisfiedByTable is the table that holds the satisfied_by relation/edge.
	SatisfiedByTable = "chapters"
	// SatisfiedByInverseTable is the table name for the SeriesProvider entity.
	// It exists in this package in order to avoid circular dependency with the "seriesprovider" package.
	SatisfiedByInverseTable = "series_providers"
	// SatisfiedByColumn is the table column denoting the satisfied_by relation/edge.
	SatisfiedByColumn = "satisfied_by_provider_id"
)

// Columns holds all SQL columns for chapter fields.
var Columns = []string{
	FieldID,
	FieldSeriesID,
	FieldChapterKey,
	FieldNumber,
	FieldState,
	FieldSatisfiedByProviderID,
	FieldSatisfiedImportance,
	FieldPageCount,
	FieldFilename,
	FieldDownloadDate,
	FieldFirstDownloadedAt,
	FieldRetries,
	FieldNextAttemptAt,
	FieldLastError,
	FieldErrorCategory,
	FieldRead,
	FieldLastReadPage,
	FieldReadAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFilename holds the default value on creation for the "filename" field.
	DefaultFilename string
	// DefaultRetries holds the default value on creation for the "retries" field.
	DefaultRetries int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultErrorCategory holds the default value on creation for the "error_category" field.
	DefaultErrorCategory string
	// DefaultRead holds the default value on creation for the "read" field.
	DefaultRead bool
	// DefaultLastReadPage holds the default value on creation for the "last_read_page" field.
	DefaultLastReadPage int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// State defines the type for the "state" enum field.
type State string

// StateWanted is the default value of the State enum.
const DefaultState = StateWanted

// State values.
const (
	StateWanted            State = "wanted"
	StateDownloading       State = "downloading"
	StateDownloaded        State = "downloaded"
	StateUpgradeAvailable  State = "upgrade_available"
	StateUpgrading         State = "upgrading"
	StateFailed            State = "failed"
	StatePermanentlyFailed State = "permanently_failed"
	StateSuperseded        State = "superseded"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateWanted, StateDownloading, StateDownloaded, StateUpgradeAvailable, StateUpgrading, StateFailed, StatePermanentlyFailed, StateSuperseded:
		return nil
	default:
		return fmt.Errorf("chapter: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Chapter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySeriesID orders the results by the series_id field.
func BySeriesID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeriesID, opts...).ToFunc()
}

// ByChapterKey orders the results by the chapter_key field.
func ByChapterKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChapterKey, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// BySatisfiedByProviderID orders the results by the satisfied_by_provider_id field.
func BySatisfiedByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSatisfiedByProviderID, opts...).ToFunc()
}

// BySatisfiedImportance orders the results by the satisfied_importance field.
func BySatisfiedImportance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSatisfiedImportance, opts...).ToFunc()
}

// ByPageCount orders the results by the page_count field.
func ByPageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageCount, opts...).ToFunc()
}

// ByFilename orders the results by the filename field.
func ByFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilename, opts...).ToFunc()
}

// ByDownloadDate orders the results by the download_date field.
func ByDownloadDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadDate, opts...).ToFunc()
}

// ByFirstDownloadedAt orders the results by the first_downloaded_at field.
func ByFirstDownloadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstDownloadedAt, opts...).ToFunc()
}

// ByRetries orders the results by the retries field.
func ByRetries(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetries, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByErrorCategory orders the results by the error_category field.
func ByErrorCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCategory, opts...).ToFunc()
}

// ByRead orders the results by the read field.
func ByRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRead, opts...).ToFunc()
}

// ByLastReadPage orders the results by the last_read_page field.
func ByLastReadPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReadPage, opts...).ToFunc()
}

// ByReadAt orders the results by the read_at field.
func ByReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadAt, opts...).ToFunc()
}

// BySeriesField orders the results by series field.
func BySeriesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeriesStep(), sql.OrderByField(field, opts...))
	}
}

// BySatisfiedByField orders the results by satisfied_by field.
func BySatisfiedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSatisfiedByStep(), sql.OrderByField(field, opts...))
	}
}
func newSeriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SeriesTable, SeriesColumn),
	)
}
func newSatisfiedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SatisfiedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SatisfiedByTable, SatisfiedByColumn),
	)
}
