// Code generated by ent, DO NOT EDIT.

package sourcethroughputpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/technobecet/tsundoku/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldSourceID, v))
}

// DownloadConcurrency applies equality check predicate on the "download_concurrency" field. It's identical to DownloadConcurrencyEQ.
func DownloadConcurrency(v int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldDownloadConcurrency, v))
}

// ImageRequestDelayMs applies equality check predicate on the "image_request_delay_ms" field. It's identical to ImageRequestDelayMsEQ.
func ImageRequestDelayMs(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldImageRequestDelayMs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLTE(FieldSourceID, v))
}

// DownloadConcurrencyEQ applies the EQ predicate on the "download_concurrency" field.
func DownloadConcurrencyEQ(v int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldDownloadConcurrency, v))
}

// DownloadConcurrencyNEQ applies the NEQ predicate on the "download_concurrency" field.
func DownloadConcurrencyNEQ(v int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNEQ(FieldDownloadConcurrency, v))
}

// DownloadConcurrencyIn applies the In predicate on the "download_concurrency" field.
func DownloadConcurrencyIn(vs ...int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIn(FieldDownloadConcurrency, vs...))
}

// DownloadConcurrencyNotIn applies the NotIn predicate on the "download_concurrency" field.
func DownloadConcurrencyNotIn(vs ...int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotIn(FieldDownloadConcurrency, vs...))
}

// DownloadConcurrencyGT applies the GT predicate on the "download_concurrency" field.
func DownloadConcurrencyGT(v int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGT(FieldDownloadConcurrency, v))
}

// DownloadConcurrencyGTE applies the GTE predicate on the "download_concurrency" field.
func DownloadConcurrencyGTE(v int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGTE(FieldDownloadConcurrency, v))
}

// DownloadConcurrencyLT applies the LT predicate on the "download_concurrency" field.
func DownloadConcurrencyLT(v int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLT(FieldDownloadConcurrency, v))
}

// DownloadConcurrencyLTE applies the LTE predicate on the "download_concurrency" field.
func DownloadConcurrencyLTE(v int) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLTE(FieldDownloadConcurrency, v))
}

// DownloadConcurrencyIsNil applies the IsNil predicate on the "download_concurrency" field.
func DownloadConcurrencyIsNil() predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIsNull(FieldDownloadConcurrency))
}

// DownloadConcurrencyNotNil applies the NotNil predicate on the "download_concurrency" field.
func DownloadConcurrencyNotNil() predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotNull(FieldDownloadConcurrency))
}

// ImageRequestDelayMsEQ applies the EQ predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsEQ(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldImageRequestDelayMs, v))
}

// ImageRequestDelayMsNEQ applies the NEQ predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsNEQ(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNEQ(FieldImageRequestDelayMs, v))
}

// ImageRequestDelayMsIn applies the In predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsIn(vs ...int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIn(FieldImageRequestDelayMs, vs...))
}

// ImageRequestDelayMsNotIn applies the NotIn predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsNotIn(vs ...int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotIn(FieldImageRequestDelayMs, vs...))
}

// ImageRequestDelayMsGT applies the GT predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsGT(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGT(FieldImageRequestDelayMs, v))
}

// ImageRequestDelayMsGTE applies the GTE predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsGTE(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGTE(FieldImageRequestDelayMs, v))
}

// ImageRequestDelayMsLT applies the LT predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsLT(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLT(FieldImageRequestDelayMs, v))
}

// ImageRequestDelayMsLTE applies the LTE predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsLTE(v int64) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLTE(FieldImageRequestDelayMs, v))
}

// ImageRequestDelayMsIsNil applies the IsNil predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsIsNil() predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIsNull(FieldImageRequestDelayMs))
}

// ImageRequestDelayMsNotNil applies the NotNil predicate on the "image_request_delay_ms" field.
func ImageRequestDelayMsNotNil() predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotNull(FieldImageRequestDelayMs))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SourceThroughputPolicy) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SourceThroughputPolicy) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SourceThroughputPolicy) predicate.SourceThroughputPolicy {
	return predicate.SourceThroughputPolicy(sql.NotPredicates(p))
}
